// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `DotnetSdkDevID` scalar type represents an identifier for an object of type DotnetSdkDev.
type DotnetSDKDevID string // dotnet-sdk-dev (../../../../:0:0)

// Retrieve the binding value, as type DotnetSdkDev
func (r *Binding) AsDotnetSDKDev() *DotnetSDKDev { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("asDotnetSdkDev")

	return &DotnetSDKDev{
		query: q,
	}
}

type DotnetSDKDev struct { // dotnet-sdk-dev (../../../../:0:0)
	query *querybuilder.Selection

	csharpier  *Void
	id         *DotnetSDKDevID
	sourcePath *string
	test       *Void
}
type WithDotnetSDKDevFunc func(r *DotnetSDKDev) *DotnetSDKDev

// With calls the provided function with current DotnetSDKDev.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *DotnetSDKDev) With(f WithDotnetSDKDevFunc) *DotnetSDKDev {
	return f(r)
}

func (r *DotnetSDKDev) WithGraphQLQuery(q *querybuilder.Selection) *DotnetSDKDev {
	return &DotnetSDKDev{
		query: q,
	}
}

// Bump dagger engine version for the Dotnet SDK
// NOTE: this is currently a no-op
func (r *DotnetSDKDev) Bump() *Changeset { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("bump")

	return &Changeset{
		query: q,
	}
}

// Return the changeset between the local workspace and the moduele's
// current workspace.
//
// For example: this can be called after `withFormat` to upload the formatted
// code on the host.
func (r *DotnetSDKDev) Changes() *Changeset { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("changes")

	return &Changeset{
		query: q,
	}
}

// Lint the Dotnet SDK with Csharpier (https://csharpier.com)
func (r *DotnetSDKDev) Csharpier(ctx context.Context) error { // dotnet-sdk-dev (../../../../:0:0)
	if r.csharpier != nil {
		return nil
	}
	q := r.query.Select("csharpier")

	return q.Execute(ctx)
}

// Return the Dotnet SDK workspace mounted in a dev container,
// and working directory set to the SDK source.
func (r *DotnetSDKDev) DevContainer() *Container { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("devContainer")

	return &Container{
		query: q,
	}
}

// A unique identifier for this DotnetSdkDev.
func (r *DotnetSDKDev) ID(ctx context.Context) (DotnetSDKDevID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response DotnetSDKDevID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *DotnetSDKDev) XXX_GraphQLType() string {
	return "DotnetSdkDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *DotnetSDKDev) XXX_GraphQLIDType() string {
	return "DotnetSDKDevID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *DotnetSDKDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *DotnetSDKDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *DotnetSDKDev) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadDotnetSDKDevFromID(DotnetSDKDevID(id))
	return nil
}

// Install the SDK locally so it can be imported.
//
// This function generate `introspection.json` which allows using
// SDK from a local checkout.
//
// Since the SDK at this moment cannot be published or installed, the
// standard function does not need to exist.
func (r *DotnetSDKDev) Install() *Changeset { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("install")

	return &Changeset{
		query: q,
	}
}

// The path of the SDK in the workspace.
func (r *DotnetSDKDev) SourcePath(ctx context.Context) (string, error) { // dotnet-sdk-dev (../../../../:0:0)
	if r.sourcePath != nil {
		return *r.sourcePath, nil
	}
	q := r.query.Select("sourcePath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Run tests on the Dotnet SDK
func (r *DotnetSDKDev) Test(ctx context.Context) error { // dotnet-sdk-dev (../../../../:0:0)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")

	return q.Execute(ctx)
}

// Run csharpier (https://csharpier.com) on the SDK source code
// and save it back to the workspace.
func (r *DotnetSDKDev) WithFormat() *DotnetSDKDev { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("withFormat")

	return &DotnetSDKDev{
		query: q,
	}
}

func (r *DotnetSDKDev) WithInstall() *DotnetSDKDev { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("withInstall")

	return &DotnetSDKDev{
		query: q,
	}
}

// A directory with all the files needed to develop the SDK.
func (r *DotnetSDKDev) Workspace() *Directory { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("workspace")

	return &Directory{
		query: q,
	}
}

// Create or update a binding of type DotnetSdkDev in the environment
func (r *Env) WithDotnetSDKDevInput(name string, value *DotnetSDKDev, description string) *Env { // dotnet-sdk-dev (../../../../:0:0)
	assertNotNil("value", value)
	q := r.query.Select("withDotnetSdkDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired DotnetSdkDev output to be assigned in the environment
func (r *Env) WithDotnetSDKDevOutput(name string, description string) *Env { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("withDotnetSdkDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// DotnetSDKDevOpts contains options for Query.DotnetSDKDev
type DotnetSDKDevOpts struct {
	//
	// A directory with all the files needed to develop the SDK.
	//
	Workspace *Directory // dotnet-sdk-dev (../../../../:0:0)
	//
	// The path of the SDK in the workspace.
	//
	SourcePath string // dotnet-sdk-dev (../../../../:0:0)
}

func (r *Query) DotnetSDKDev(opts ...DotnetSDKDevOpts) *DotnetSDKDev { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("dotnetSdkDev")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `sourcePath` optional argument
		if !querybuilder.IsZeroValue(opts[i].SourcePath) {
			q = q.Arg("sourcePath", opts[i].SourcePath)
		}
	}

	return &DotnetSDKDev{
		query: q,
	}
}

// Load a DotnetSdkDev from its ID.
func (r *Query) LoadDotnetSDKDevFromID(id DotnetSDKDevID) *DotnetSDKDev { // dotnet-sdk-dev (../../../../:0:0)
	q := r.query.Select("loadDotnetSdkDevFromID")
	q = q.Arg("id", id)

	return &DotnetSDKDev{
		query: q,
	}
}
