// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `PythonSdkDevDocsID` scalar type represents an identifier for an object of type PythonSdkDevDocs.
type PythonSDKDevDocsID string // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)

// The `PythonSdkDevID` scalar type represents an identifier for an object of type PythonSdkDev.
type PythonSDKDevID string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)

// The `PythonSdkDevTestForPythonVersionID` scalar type represents an identifier for an object of type PythonSdkDevTestForPythonVersion.
type PythonSDKDevTestForPythonVersionID string // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:9:6)

// Retrieve the binding value, as type PythonSdkDev
func (r *Binding) AsPythonSDKDev() *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	q := r.query.Select("asPythonSdkDev")

	return &PythonSDKDev{
		query: q,
	}
}

// Retrieve the binding value, as type PythonSdkDevDocs
func (r *Binding) AsPythonSDKDevDocs() *PythonSDKDevDocs { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	q := r.query.Select("asPythonSdkDevDocs")

	return &PythonSDKDevDocs{
		query: q,
	}
}

// Retrieve the binding value, as type PythonSdkDevTestForPythonVersion
func (r *Binding) AsPythonSDKDevTestForPythonVersion() *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:9:6)
	q := r.query.Select("asPythonSdkDevTestForPythonVersion")

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDevDocs in the environment
func (r *Env) WithPythonSDKDevDocsInput(name string, value *PythonSDKDevDocs, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevDocsInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDevDocs output to be assigned in the environment
func (r *Env) WithPythonSDKDevDocsOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	q := r.query.Select("withPythonSdkDevDocsOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDev in the environment
func (r *Env) WithPythonSDKDevInput(name string, value *PythonSDKDev, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDev output to be assigned in the environment
func (r *Env) WithPythonSDKDevOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	q := r.query.Select("withPythonSdkDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PythonSdkDevTestForPythonVersion in the environment
func (r *Env) WithPythonSDKDevTestForPythonVersionInput(name string, value *PythonSDKDevTestForPythonVersion, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:9:6)
	assertNotNil("value", value)
	q := r.query.Select("withPythonSdkDevTestForPythonVersionInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PythonSdkDevTestForPythonVersion output to be assigned in the environment
func (r *Env) WithPythonSDKDevTestForPythonVersionOutput(name string, description string) *Env { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:9:6)
	q := r.query.Select("withPythonSdkDevTestForPythonVersionOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// A toolchain to develop the Dagger Python SDK
type PythonSDKDev struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	query *querybuilder.Selection

	id            *PythonSDKDevID
	release       *Void
	releaseDryRun *Void
	sourcePath    *string
	typecheck     *Void
}
type WithPythonSDKDevFunc func(r *PythonSDKDev) *PythonSDKDev

// With calls the provided function with current PythonSDKDev.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *PythonSDKDev) With(f WithPythonSDKDevFunc) *PythonSDKDev {
	return f(r)
}

func (r *PythonSDKDev) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDev {
	return &PythonSDKDev{
		query: q,
	}
}

// PythonSDKDevBuildOpts contains options for PythonSDKDev.Build
type PythonSDKDevBuildOpts struct {
	//
	// The version for the distribution package
	//
	//
	// Default: "0.0.0"
	Version string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:283:2)
}

// Build the Python SDK client library package for distribution
func (r *PythonSDKDev) Build(opts ...PythonSDKDevBuildOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:280:1)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Container{
		query: q,
	}
}

// Bump the Python SDK's Engine dependency
func (r *PythonSDKDev) Bump(version string) *Changeset { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:268:1)
	q := r.query.Select("bump")
	q = q.Arg("version", version)

	return &Changeset{
		query: q,
	}
}

// Regenerate the core Python client library
func (r *PythonSDKDev) ClientLibrary() *Changeset { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:175:1)
	q := r.query.Select("clientLibrary")

	return &Changeset{
		query: q,
	}
}

// Python container to develop Python SDK
func (r *PythonSDKDev) DevContainer() *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:17:2)
	q := r.query.Select("devContainer")

	return &Container{
		query: q,
	}
}

// Preview the reference documentation
func (r *PythonSDKDev) Docs() *PythonSDKDevDocs { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:321:1)
	q := r.query.Select("docs")

	return &PythonSDKDevDocs{
		query: q,
	}
}

// PythonSDKDevFormatOpts contains options for PythonSDKDev.Format
type PythonSDKDevFormatOpts struct {
	//
	// List of files or directories to check
	//
	Paths []string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:104:2)
}

// Format source files
func (r *PythonSDKDev) Format(opts ...PythonSDKDevFormatOpts) *Changeset { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:101:1)
	q := r.query.Select("format")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
	}

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this PythonSdkDev.
func (r *PythonSDKDev) ID(ctx context.Context) (PythonSDKDevID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response PythonSDKDevID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDev) XXX_GraphQLType() string {
	return "PythonSdkDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDev) XXX_GraphQLIDType() string {
	return "PythonSDKDevID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDev) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadPythonSDKDevFromID(PythonSDKDevID(id))
	return nil
}

// PythonSDKDevLintOpts contains options for PythonSDKDev.Lint
type PythonSDKDevLintOpts struct {
	//
	// List of files or directories to check
	//
	Paths []string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:92:2)
}

// Check for linting errors
func (r *PythonSDKDev) Lint(opts ...PythonSDKDevLintOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:89:1)
	q := r.query.Select("lint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
	}

	return &Container{
		query: q,
	}
}

// PythonSDKDevLintDocsSnippetsOpts contains options for PythonSDKDev.LintDocsSnippets
type PythonSDKDevLintDocsSnippetsOpts struct {
	Workspace *Directory // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:81:2)
}

// Lint the Python snippets in the documentation
func (r *PythonSDKDev) LintDocsSnippets(opts ...PythonSDKDevLintDocsSnippetsOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:74:1)
	q := r.query.Select("lintDocsSnippets")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	return &Container{
		query: q,
	}
}

// PythonSDKDevProvisionOpts contains options for PythonSDKDev.Provision
type PythonSDKDevProvisionOpts struct {
	//
	// _EXPERIMENTAL_DAGGER_RUNNER_HOST value
	//
	RunnerHost string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:333:2)
}

func (r *PythonSDKDev) Provision(cliBin *File, opts ...PythonSDKDevProvisionOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:327:1)
	assertNotNil("cliBin", cliBin)
	q := r.query.Select("provision")
	for i := len(opts) - 1; i >= 0; i-- {
		// `runnerHost` optional argument
		if !querybuilder.IsZeroValue(opts[i].RunnerHost) {
			q = q.Arg("runnerHost", opts[i].RunnerHost)
		}
	}
	q = q.Arg("cliBin", cliBin)

	return &Container{
		query: q,
	}
}

// PythonSDKDevPublishOpts contains options for PythonSDKDev.Publish
type PythonSDKDevPublishOpts struct {
	//
	// The version for the distribution package to publish
	//
	//
	// Default: "0.0.0"
	Version string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:297:2)
	//
	// The URL of the upload endpoint (empty means PyPI)
	//
	URL string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:300:2)
}

// Publish Python SDK client library to PyPI
func (r *PythonSDKDev) Publish(token *Secret, opts ...PythonSDKDevPublishOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:292:1)
	assertNotNil("token", token)
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `url` optional argument
		if !querybuilder.IsZeroValue(opts[i].URL) {
			q = q.Arg("url", opts[i].URL)
		}
	}
	q = q.Arg("token", token)

	return &Container{
		query: q,
	}
}

// Test suite for python 3.10
func (r *PythonSDKDev) Python310() *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:134:1)
	q := r.query.Select("python310")

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// Test suite for python 3.11
func (r *PythonSDKDev) Python311() *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:142:1)
	q := r.query.Select("python311")

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// Test suite for python 3.12
func (r *PythonSDKDev) Python312() *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:150:1)
	q := r.query.Select("python312")

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// Test suite for python 3.13
func (r *PythonSDKDev) Python313() *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:158:1)
	q := r.query.Select("python313")

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// Test suite for python 3.14
func (r *PythonSDKDev) Python314() *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:166:1)
	q := r.query.Select("python314")

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// PythonSDKDevReleaseOpts contains options for PythonSDKDev.Release
type PythonSDKDevReleaseOpts struct {
	DryRun bool // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:239:2)

	PypiRepo string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:242:2)

	PypiToken *Secret // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:245:2)
}

// Release the Python SDK
func (r *PythonSDKDev) Release(ctx context.Context, sourceTag string, opts ...PythonSDKDevReleaseOpts) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:232:1)
	if r.release != nil {
		return nil
	}
	q := r.query.Select("release")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
		// `pypiRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiRepo) {
			q = q.Arg("pypiRepo", opts[i].PypiRepo)
		}
		// `pypiToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiToken) {
			q = q.Arg("pypiToken", opts[i].PypiToken)
		}
	}
	q = q.Arg("sourceTag", sourceTag)

	return q.Execute(ctx)
}

// Test the publishing process
func (r *PythonSDKDev) ReleaseDryRun(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:221:1)
	if r.releaseDryRun != nil {
		return nil
	}
	q := r.query.Select("releaseDryRun")

	return q.Execute(ctx)
}

func (r *PythonSDKDev) SourcePath(ctx context.Context) (string, error) { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:19:2)
	if r.sourcePath != nil {
		return *r.sourcePath, nil
	}
	q := r.query.Select("sourcePath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Supported Python versions
func (r *PythonSDKDev) SupportedVersions(ctx context.Context) ([]string, error) { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:21:2)
	q := r.query.Select("supportedVersions")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// PythonSDKDevTestPublishOpts contains options for PythonSDKDev.TestPublish
type PythonSDKDevTestPublishOpts struct {
	//
	// The version for the distribution package to publish
	//
	//
	// Default: "0.0.0"
	Version string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:315:2)
}

// Test the publishing of the Python SDK client library to TestPyPI
func (r *PythonSDKDev) TestPublish(token *Secret, opts ...PythonSDKDevTestPublishOpts) *Container { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:310:1)
	assertNotNil("token", token)
	q := r.query.Select("testPublish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}
	q = q.Arg("token", token)

	return &Container{
		query: q,
	}
}

// Run the type checker (mypy)
// FIXME: this is not included as an automated check. Should it?
func (r *PythonSDKDev) Typecheck(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:116:1)
	if r.typecheck != nil {
		return nil
	}
	q := r.query.Select("typecheck")

	return q.Execute(ctx)
}

// Mount a directory on the base container
func (r *PythonSDKDev) WithDirectory(source *Directory) *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:125:1)
	assertNotNil("source", source)
	q := r.query.Select("withDirectory")
	q = q.Arg("source", source)

	return &PythonSDKDev{
		query: q,
	}
}

func (r *PythonSDKDev) Workspace() *Directory { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:18:2)
	q := r.query.Select("workspace")

	return &Directory{
		query: q,
	}
}

type PythonSDKDevDocs struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	query *querybuilder.Selection

	id *PythonSDKDevDocsID
}

func (r *PythonSDKDevDocs) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDevDocs {
	return &PythonSDKDevDocs{
		query: q,
	}
}

// Build the documentation
func (r *PythonSDKDevDocs) Build() *Directory { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:15:1)
	q := r.query.Select("build")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this PythonSdkDevDocs.
func (r *PythonSDKDevDocs) ID(ctx context.Context) (PythonSDKDevDocsID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response PythonSDKDevDocsID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDevDocs) XXX_GraphQLType() string {
	return "PythonSdkDevDocs"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDevDocs) XXX_GraphQLIDType() string {
	return "PythonSDKDevDocsID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDevDocs) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDevDocs) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDevDocs) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadPythonSDKDevDocsFromID(PythonSDKDevDocsID(id))
	return nil
}

// PythonSDKDevDocsPreviewOpts contains options for PythonSDKDevDocs.Preview
type PythonSDKDevDocsPreviewOpts struct {
	//
	// The port to bind the web preview for the built docs
	//
	//
	// Default: 8000
	Bind int // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:28:2)
}

// Build and preview the documentation in the browser
func (r *PythonSDKDevDocs) Preview(opts ...PythonSDKDevDocsPreviewOpts) *Service { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:25:1)
	q := r.query.Select("preview")
	for i := len(opts) - 1; i >= 0; i-- {
		// `bind` optional argument
		if !querybuilder.IsZeroValue(opts[i].Bind) {
			q = q.Arg("bind", opts[i].Bind)
		}
	}

	return &Service{
		query: q,
	}
}

type PythonSDKDevTestForPythonVersion struct { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:9:6)
	query *querybuilder.Selection

	id   *PythonSDKDevTestForPythonVersionID
	run  *Void
	slow *Void
	unit *Void
}

func (r *PythonSDKDevTestForPythonVersion) WithGraphQLQuery(q *querybuilder.Selection) *PythonSDKDevTestForPythonVersion {
	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// A unique identifier for this PythonSdkDevTestForPythonVersion.
func (r *PythonSDKDevTestForPythonVersion) ID(ctx context.Context) (PythonSDKDevTestForPythonVersionID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response PythonSDKDevTestForPythonVersionID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PythonSDKDevTestForPythonVersion) XXX_GraphQLType() string {
	return "PythonSdkDevTestForPythonVersion"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PythonSDKDevTestForPythonVersion) XXX_GraphQLIDType() string {
	return "PythonSDKDevTestForPythonVersionID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PythonSDKDevTestForPythonVersion) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PythonSDKDevTestForPythonVersion) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PythonSDKDevTestForPythonVersion) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadPythonSDKDevTestForPythonVersionFromID(PythonSDKDevTestForPythonVersionID(id))
	return nil
}

// Run the pytest command.
func (r *PythonSDKDevTestForPythonVersion) Run(ctx context.Context, args []string) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:31:1)
	if r.run != nil {
		return nil
	}
	q := r.query.Select("run")
	q = q.Arg("args", args)

	return q.Execute(ctx)
}

// Run python slow tests
func (r *PythonSDKDevTestForPythonVersion) Slow(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:20:1)
	if r.slow != nil {
		return nil
	}
	q := r.query.Select("slow")

	return q.Execute(ctx)
}

// Run python unit tests
func (r *PythonSDKDevTestForPythonVersion) Unit(ctx context.Context) error { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:26:1)
	if r.unit != nil {
		return nil
	}
	q := r.query.Select("unit")

	return q.Execute(ctx)
}

// Load a PythonSdkDevDocs from its ID.
func (r *Query) LoadPythonSDKDevDocsFromID(id PythonSDKDevDocsID) *PythonSDKDevDocs { // python-sdk-dev (../../../../toolchains/python-sdk-dev/docs.go:9:6)
	q := r.query.Select("loadPythonSdkDevDocsFromID")
	q = q.Arg("id", id)

	return &PythonSDKDevDocs{
		query: q,
	}
}

// Load a PythonSdkDev from its ID.
func (r *Query) LoadPythonSDKDevFromID(id PythonSDKDevID) *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:15:6)
	q := r.query.Select("loadPythonSdkDevFromID")
	q = q.Arg("id", id)

	return &PythonSDKDev{
		query: q,
	}
}

// Load a PythonSdkDevTestForPythonVersion from its ID.
func (r *Query) LoadPythonSDKDevTestForPythonVersionFromID(id PythonSDKDevTestForPythonVersionID) *PythonSDKDevTestForPythonVersion { // python-sdk-dev (../../../../toolchains/python-sdk-dev/test.go:9:6)
	q := r.query.Select("loadPythonSdkDevTestForPythonVersionFromID")
	q = q.Arg("id", id)

	return &PythonSDKDevTestForPythonVersion{
		query: q,
	}
}

// PythonSDKDevOpts contains options for Query.PythonSDKDev
type PythonSDKDevOpts struct {
	//
	// A workspace containing the SDK source code and other relevant files
	//
	Workspace *Directory // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:45:2)

	// Default: "sdk/python"
	SourcePath string // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:48:2)
}

// A toolchain to develop the Dagger Python SDK
func (r *Query) PythonSDKDev(opts ...PythonSDKDevOpts) *PythonSDKDev { // python-sdk-dev (../../../../toolchains/python-sdk-dev/main.go:24:1)
	q := r.query.Select("pythonSdkDev")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `sourcePath` optional argument
		if !querybuilder.IsZeroValue(opts[i].SourcePath) {
			q = q.Arg("sourcePath", opts[i].SourcePath)
		}
	}

	return &PythonSDKDev{
		query: q,
	}
}
