name = "typescript-sdk-dev"
engineVersion = "v0.21.7"
include = ["is-semver"]

[runtime]
  source = "dang"

[[dependencies]]
  name = "codegen"
  source = "../../cmd/codegen"

[[dependencies]]
  name = "dagger-engine"
  source = "../engine-dev"

[[dependencies]]
  name = "go"
  source = "../go"
