# frozen_string_literal: true

source "https://rubygems.org"

gem 'base64', '~> 0.2.0'
gem 'sorbet-runtime', '~> 0.5.0'
gem 'json', '~> 2.8.2'
gem 'sorbet', '~> 0.5.0', :group => :development
gem 'tapioca', '~> 0.16.0', :group => :development
