# syntax = docker/dockerfile:1.2

FROM golang:1.18.2-alpine AS build
WORKDIR /src
RUN apk add --no-cache file git
ENV GOMODCACHE /root/.cache/gocache
RUN --mount=target=. --mount=target=/root/.cache,type=cache \
    CGO_ENABLED=0 go build -o /out -ldflags '-s -d -w' ./examples/netlify

FROM scratch
COPY --from=build /out /entrypoint
ENTRYPOINT ["/entrypoint"]
LABEL moby.buildkit.frontend.caps=moby.buildkit.frontend.inputs
