// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Helm
func (r *Binding) AsHelm() *Helm { // helm (../../../:0:0)
	q := r.query.Select("asHelm")

	return &Helm{
		query: q,
	}
}

// Retrieve the binding value, as type HelmChart
func (r *Binding) AsHelmChart() *HelmChart { // helm (../../../:0:0)
	q := r.query.Select("asHelmChart")

	return &HelmChart{
		query: q,
	}
}

// Retrieve the binding value, as type HelmChartValues
func (r *Binding) AsHelmChartValues() *HelmChartValues { // helm (../../../:0:0)
	q := r.query.Select("asHelmChartValues")

	return &HelmChartValues{
		query: q,
	}
}

// Create or update a binding of type HelmChart in the environment
func (r *Env) WithHelmChartInput(name string, value *HelmChart, description string) *Env { // helm (../../../:0:0)
	assertNotNil("value", value)
	q := r.query.Select("withHelmChartInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HelmChart output to be assigned in the environment
func (r *Env) WithHelmChartOutput(name string, description string) *Env { // helm (../../../:0:0)
	q := r.query.Select("withHelmChartOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HelmChartValues in the environment
func (r *Env) WithHelmChartValuesInput(name string, value *HelmChartValues, description string) *Env { // helm (../../../:0:0)
	assertNotNil("value", value)
	q := r.query.Select("withHelmChartValuesInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HelmChartValues output to be assigned in the environment
func (r *Env) WithHelmChartValuesOutput(name string, description string) *Env { // helm (../../../:0:0)
	q := r.query.Select("withHelmChartValuesOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Helm in the environment
func (r *Env) WithHelmInput(name string, value *Helm, description string) *Env { // helm (../../../:0:0)
	assertNotNil("value", value)
	q := r.query.Select("withHelmInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Helm output to be assigned in the environment
func (r *Env) WithHelmOutput(name string, description string) *Env { // helm (../../../:0:0)
	q := r.query.Select("withHelmOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// A Dagger module for Helm: a package manager for Kubernetes. https://helm.sh
type Helm struct { // helm (../../../:0:0)
	query *querybuilder.Selection

	assertTemplate *Void
	id             *ID
	lint           *Void
	valuesGlob     *string
	version        *string
}

func (r *Helm) WithGraphQLQuery(q *querybuilder.Selection) *Helm {
	return &Helm{
		query: q,
	}
}

// HelmAssertTemplateOpts contains options for Helm.AssertTemplate
type HelmAssertTemplateOpts struct {
	Ws *Workspace // helm (../../../:0:0)
}

// Assert every discovered values file renders with helm template --dry-run=client.
func (r *Helm) AssertTemplate(ctx context.Context, opts ...HelmAssertTemplateOpts) error { // helm (../../../:0:0)
	if r.assertTemplate != nil {
		return nil
	}
	q := r.query.Select("assertTemplate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return q.Execute(ctx)
}

// HelmChartOpts contains options for Helm.Chart
type HelmChartOpts struct {
	Ws *Workspace // helm (../../../:0:0)
}

// Return one discovered chart by its workspace-relative path.
func (r *Helm) Chart(path string, opts ...HelmChartOpts) *HelmChart { // helm (../../../:0:0)
	q := r.query.Select("chart")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}
	q = q.Arg("path", path)

	return &HelmChart{
		query: q,
	}
}

// HelmChartsOpts contains options for Helm.Charts
type HelmChartsOpts struct {
	Ws *Workspace // helm (../../../:0:0)
}

// Scan the workspace for Helm charts.
func (r *Helm) Charts(ctx context.Context, opts ...HelmChartsOpts) ([]HelmChart, error) { // helm (../../../:0:0)
	q := r.query.Select("charts")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	q = q.Select("id")

	type charts struct {
		Id ID
	}

	convert := func(fields []charts) []HelmChart {
		out := []HelmChart{}

		for i := range fields {
			val := HelmChart{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "HelmChart")
			out = append(out, val)
		}

		return out
	}
	var response []charts

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// A unique identifier for this Helm.
func (r *Helm) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Helm) XXX_GraphQLType() string {
	return "Helm"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Helm) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Helm) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Helm) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Helm) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Helm{query: selectNode(dag.query, id, "Helm")}
	return nil
}

// HelmLintOpts contains options for Helm.Lint
type HelmLintOpts struct {
	Ws *Workspace // helm (../../../:0:0)
}

// Lint every discovered Helm chart in the workspace.
func (r *Helm) Lint(ctx context.Context, opts ...HelmLintOpts) error { // helm (../../../:0:0)
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return q.Execute(ctx)
}

// Glob for chart values files to check as extra matrix dimensions.
//
// Defaults to Helm chart-testing's CI values convention:
// https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md
func (r *Helm) ValuesGlob(ctx context.Context) (string, error) { // helm (../../../:0:0)
	if r.valuesGlob != nil {
		return *r.valuesGlob, nil
	}
	q := r.query.Select("valuesGlob")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// The version of Helm to use.
func (r *Helm) Version(ctx context.Context) (string, error) { // helm (../../../:0:0)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Helm as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Helm) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A discovered Helm chart in the workspace.
type HelmChart struct { // helm (../../../:0:0)
	query *querybuilder.Selection

	assertTemplate *Void
	id             *ID
	lint           *Void
	path           *string
}

func (r *HelmChart) WithGraphQLQuery(q *querybuilder.Selection) *HelmChart {
	return &HelmChart{
		query: q,
	}
}

// Assert every discovered values file renders with helm template --dry-run=client.
//
// This intentionally skips the bare chart. Some charts only render cleanly
// with one of their explicit values files.
func (r *HelmChart) AssertTemplate(ctx context.Context) error { // helm (../../../:0:0)
	if r.assertTemplate != nil {
		return nil
	}
	q := r.query.Select("assertTemplate")

	return q.Execute(ctx)
}

// A unique identifier for this HelmChart.
func (r *HelmChart) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HelmChart) XXX_GraphQLType() string {
	return "HelmChart"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HelmChart) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HelmChart) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HelmChart) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HelmChart) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HelmChart{query: selectNode(dag.query, id, "HelmChart")}
	return nil
}

// Run helm lint on this chart.
func (r *HelmChart) Lint(ctx context.Context) error { // helm (../../../:0:0)
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")

	return q.Execute(ctx)
}

// Path of the chart directory in the workspace.
func (r *HelmChart) Path(ctx context.Context) (string, error) { // helm (../../../:0:0)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Values dimensions for this chart's check matrix.
//
// Defaults to chart-testing's convention: chart-root ci/*-values.yaml files.
func (r *HelmChart) Values(ctx context.Context) ([]HelmChartValues, error) { // helm (../../../:0:0)
	q := r.query.Select("values")

	q = q.Select("id")

	type values struct {
		Id ID
	}

	convert := func(fields []values) []HelmChartValues {
		out := []HelmChartValues{}

		for i := range fields {
			val := HelmChartValues{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "HelmChartValues")
			out = append(out, val)
		}

		return out
	}
	var response []values

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// AsNode returns this HelmChart as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HelmChart) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// A values dimension for Helm chart checks.
type HelmChartValues struct { // helm (../../../:0:0)
	query *querybuilder.Selection

	assertTemplate *Void
	id             *ID
	lint           *Void
	path           *string
}

func (r *HelmChartValues) WithGraphQLQuery(q *querybuilder.Selection) *HelmChartValues {
	return &HelmChartValues{
		query: q,
	}
}

// Assert this values file renders with helm template --dry-run=client.
func (r *HelmChartValues) AssertTemplate(ctx context.Context) error { // helm (../../../:0:0)
	if r.assertTemplate != nil {
		return nil
	}
	q := r.query.Select("assertTemplate")

	return q.Execute(ctx)
}

// A unique identifier for this HelmChartValues.
func (r *HelmChartValues) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HelmChartValues) XXX_GraphQLType() string {
	return "HelmChartValues"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HelmChartValues) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HelmChartValues) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HelmChartValues) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HelmChartValues) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HelmChartValues{query: selectNode(dag.query, id, "HelmChartValues")}
	return nil
}

// Run helm lint for this values dimension.
func (r *HelmChartValues) Lint(ctx context.Context) error { // helm (../../../:0:0)
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")

	return q.Execute(ctx)
}

// Path to the custom values file, relative to the chart root.
func (r *HelmChartValues) Path(ctx context.Context) (string, error) { // helm (../../../:0:0)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this HelmChartValues as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HelmChartValues) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// HelmOpts contains options for Query.Helm
type HelmOpts struct {
	//
	// The version of Helm to use.
	//
	Version string // helm (../../../:0:0)
	//
	// Glob for chart values files to check as extra matrix dimensions.
	//
	// Defaults to Helm chart-testing's CI values convention:
	// https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md
	//
	ValuesGlob string // helm (../../../:0:0)
}

// A Dagger module for Helm: a package manager for Kubernetes. https://helm.sh
func (r *Query) Helm(opts ...HelmOpts) *Helm { // helm (../../../:0:0)
	q := r.query.Select("helm")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `valuesGlob` optional argument
		if !querybuilder.IsZeroValue(opts[i].ValuesGlob) {
			q = q.Arg("valuesGlob", opts[i].ValuesGlob)
		}
	}

	return &Helm{
		query: q,
	}
}
