// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Release
func (r *Binding) AsRelease() *Release { // release (../../../toolchains/release/main.go:21:6)
	q := r.query.Select("asRelease")

	return &Release{
		query: q,
	}
}

// Retrieve the binding value, as type ReleaseReport
func (r *Binding) AsReleaseReport() *ReleaseReport { // release (../../../toolchains/release/main.go:23:6)
	q := r.query.Select("asReleaseReport")

	return &ReleaseReport{
		query: q,
	}
}

// Retrieve the binding value, as type ReleaseReportArtifact
func (r *Binding) AsReleaseReportArtifact() *ReleaseReportArtifact { // release (../../../toolchains/release/main.go:36:6)
	q := r.query.Select("asReleaseReportArtifact")

	return &ReleaseReportArtifact{
		query: q,
	}
}

// Retrieve the binding value, as type ReleaseReportFollowUp
func (r *Binding) AsReleaseReportFollowUp() *ReleaseReportFollowUp { // release (../../../toolchains/release/main.go:46:6)
	q := r.query.Select("asReleaseReportFollowUp")

	return &ReleaseReportFollowUp{
		query: q,
	}
}

// Retrieve the binding value, as type ReleaseTest
func (r *Binding) AsReleaseTest() *ReleaseTest { // release (../../../toolchains/release/tests.go:27:6)
	q := r.query.Select("asReleaseTest")

	return &ReleaseTest{
		query: q,
	}
}

// Create or update a binding of type Release in the environment
func (r *Env) WithReleaseInput(name string, value *Release, description string) *Env { // release (../../../toolchains/release/main.go:21:6)
	assertNotNil("value", value)
	q := r.query.Select("withReleaseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Release output to be assigned in the environment
func (r *Env) WithReleaseOutput(name string, description string) *Env { // release (../../../toolchains/release/main.go:21:6)
	q := r.query.Select("withReleaseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type ReleaseReportArtifact in the environment
func (r *Env) WithReleaseReportArtifactInput(name string, value *ReleaseReportArtifact, description string) *Env { // release (../../../toolchains/release/main.go:36:6)
	assertNotNil("value", value)
	q := r.query.Select("withReleaseReportArtifactInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ReleaseReportArtifact output to be assigned in the environment
func (r *Env) WithReleaseReportArtifactOutput(name string, description string) *Env { // release (../../../toolchains/release/main.go:36:6)
	q := r.query.Select("withReleaseReportArtifactOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type ReleaseReportFollowUp in the environment
func (r *Env) WithReleaseReportFollowUpInput(name string, value *ReleaseReportFollowUp, description string) *Env { // release (../../../toolchains/release/main.go:46:6)
	assertNotNil("value", value)
	q := r.query.Select("withReleaseReportFollowUpInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ReleaseReportFollowUp output to be assigned in the environment
func (r *Env) WithReleaseReportFollowUpOutput(name string, description string) *Env { // release (../../../toolchains/release/main.go:46:6)
	q := r.query.Select("withReleaseReportFollowUpOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type ReleaseReport in the environment
func (r *Env) WithReleaseReportInput(name string, value *ReleaseReport, description string) *Env { // release (../../../toolchains/release/main.go:23:6)
	assertNotNil("value", value)
	q := r.query.Select("withReleaseReportInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ReleaseReport output to be assigned in the environment
func (r *Env) WithReleaseReportOutput(name string, description string) *Env { // release (../../../toolchains/release/main.go:23:6)
	q := r.query.Select("withReleaseReportOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type ReleaseTest in the environment
func (r *Env) WithReleaseTestInput(name string, value *ReleaseTest, description string) *Env { // release (../../../toolchains/release/tests.go:27:6)
	assertNotNil("value", value)
	q := r.query.Select("withReleaseTestInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ReleaseTest output to be assigned in the environment
func (r *Env) WithReleaseTestOutput(name string, description string) *Env { // release (../../../toolchains/release/tests.go:27:6)
	q := r.query.Select("withReleaseTestOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// A module that encodes the official release process of the Dagger Engine
func (r *Query) Release() *Release { // release (../../../toolchains/release/main.go:21:6)
	q := r.query.Select("release")

	return &Release{
		query: q,
	}
}

type Release struct { // release (../../../toolchains/release/main.go:21:6)
	query *querybuilder.Selection

	id     *ID
	notify *Void
}

func (r *Release) WithGraphQLQuery(q *querybuilder.Selection) *Release {
	return &Release{
		query: q,
	}
}

// Change the required dagger engine version across all components
func (r *Release) Bump(engineVersion string) *Changeset { // release (../../../toolchains/release/bump.go:11:1)
	q := r.query.Select("bump")
	q = q.Arg("engineVersion", engineVersion)

	return &Changeset{
		query: q,
	}
}

// ReleaseGetMaintainersOpts contains options for Release.GetMaintainers
type ReleaseGetMaintainersOpts struct {
	GithubToken *Secret // release (../../../toolchains/release/changie.go:28:2)
}

func (r *Release) GetMaintainers(ctx context.Context, githubOrgName string, opts ...ReleaseGetMaintainersOpts) ([]string, error) { // release (../../../toolchains/release/changie.go:24:1)
	q := r.query.Select("getMaintainers")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
	}
	q = q.Arg("githubOrgName", githubOrgName)

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Release.
func (r *Release) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Release) XXX_GraphQLType() string {
	return "Release"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Release) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Release) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Release) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Release) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Release{query: selectNode(dag.query, id, "Release")}
	return nil
}

// ReleaseNotifyOpts contains options for Release.Notify
type ReleaseNotifyOpts struct {
	//
	// Discord webhook
	//
	DiscordWebhook *Secret // release (../../../toolchains/release/main.go:443:2)
	//
	// Whether to perform a dry run without creating the release
	//
	DryRun bool // release (../../../toolchains/release/main.go:447:2)
}

func (r *Release) Notify(ctx context.Context, repository string, target string, name string, opts ...ReleaseNotifyOpts) error { // release (../../../toolchains/release/main.go:432:1)
	if r.notify != nil {
		return nil
	}
	q := r.query.Select("notify")
	for i := len(opts) - 1; i >= 0; i-- {
		// `discordWebhook` optional argument
		if !querybuilder.IsZeroValue(opts[i].DiscordWebhook) {
			q = q.Arg("discordWebhook", opts[i].DiscordWebhook)
		}
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
	}
	q = q.Arg("repository", repository)
	q = q.Arg("target", target)
	q = q.Arg("name", name)

	return q.Execute(ctx)
}

// ReleasePublishOpts contains options for Release.Publish
type ReleasePublishOpts struct {
	DryRun bool // release (../../../toolchains/release/main.go:108:2)

	RegistryImage string // release (../../../toolchains/release/main.go:110:2)

	RegistryUsername string // release (../../../toolchains/release/main.go:111:2)

	RegistryPassword *Secret // release (../../../toolchains/release/main.go:112:2)

	GoreleaserKey *Secret // release (../../../toolchains/release/main.go:114:2)

	GithubToken *Secret // release (../../../toolchains/release/main.go:116:2)

	GithubOrgName string // release (../../../toolchains/release/main.go:117:2)

	NetlifyToken *Secret // release (../../../toolchains/release/main.go:119:2)

	PypiToken *Secret // release (../../../toolchains/release/main.go:120:2)

	PypiRepo string // release (../../../toolchains/release/main.go:121:2)

	NpmToken *Secret // release (../../../toolchains/release/main.go:122:2)

	HexApikey *Secret // release (../../../toolchains/release/main.go:123:2)

	CargoRegistryToken *Secret // release (../../../toolchains/release/main.go:124:2)

	AwsAccessKeyID *Secret // release (../../../toolchains/release/main.go:126:2)

	AwsSecretAccessKey *Secret // release (../../../toolchains/release/main.go:127:2)

	AwsRegion string // release (../../../toolchains/release/main.go:128:2)

	AwsBucket string // release (../../../toolchains/release/main.go:129:2)

	AwsCloudfrontDistribution string // release (../../../toolchains/release/main.go:130:2)

	ArtefactsFqdn string // release (../../../toolchains/release/main.go:131:2)

	DiscordWebhook *Secret // release (../../../toolchains/release/main.go:133:2)
}

func (r *Release) Publish(tag string, commit string, opts ...ReleasePublishOpts) *ReleaseReport { // release (../../../toolchains/release/main.go:103:1)
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
		// `registryImage` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryImage) {
			q = q.Arg("registryImage", opts[i].RegistryImage)
		}
		// `registryUsername` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsername) {
			q = q.Arg("registryUsername", opts[i].RegistryUsername)
		}
		// `registryPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPassword) {
			q = q.Arg("registryPassword", opts[i].RegistryPassword)
		}
		// `goreleaserKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].GoreleaserKey) {
			q = q.Arg("goreleaserKey", opts[i].GoreleaserKey)
		}
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `githubOrgName` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubOrgName) {
			q = q.Arg("githubOrgName", opts[i].GithubOrgName)
		}
		// `netlifyToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].NetlifyToken) {
			q = q.Arg("netlifyToken", opts[i].NetlifyToken)
		}
		// `pypiToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiToken) {
			q = q.Arg("pypiToken", opts[i].PypiToken)
		}
		// `pypiRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiRepo) {
			q = q.Arg("pypiRepo", opts[i].PypiRepo)
		}
		// `npmToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].NpmToken) {
			q = q.Arg("npmToken", opts[i].NpmToken)
		}
		// `hexApikey` optional argument
		if !querybuilder.IsZeroValue(opts[i].HexApikey) {
			q = q.Arg("hexApikey", opts[i].HexApikey)
		}
		// `cargoRegistryToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].CargoRegistryToken) {
			q = q.Arg("cargoRegistryToken", opts[i].CargoRegistryToken)
		}
		// `awsAccessKeyId` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsAccessKeyID) {
			q = q.Arg("awsAccessKeyId", opts[i].AwsAccessKeyID)
		}
		// `awsSecretAccessKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsSecretAccessKey) {
			q = q.Arg("awsSecretAccessKey", opts[i].AwsSecretAccessKey)
		}
		// `awsRegion` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsRegion) {
			q = q.Arg("awsRegion", opts[i].AwsRegion)
		}
		// `awsBucket` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsBucket) {
			q = q.Arg("awsBucket", opts[i].AwsBucket)
		}
		// `awsCloudfrontDistribution` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsCloudfrontDistribution) {
			q = q.Arg("awsCloudfrontDistribution", opts[i].AwsCloudfrontDistribution)
		}
		// `artefactsFqdn` optional argument
		if !querybuilder.IsZeroValue(opts[i].ArtefactsFqdn) {
			q = q.Arg("artefactsFqdn", opts[i].ArtefactsFqdn)
		}
		// `discordWebhook` optional argument
		if !querybuilder.IsZeroValue(opts[i].DiscordWebhook) {
			q = q.Arg("discordWebhook", opts[i].DiscordWebhook)
		}
	}
	q = q.Arg("tag", tag)
	q = q.Arg("commit", commit)

	return &ReleaseReport{
		query: q,
	}
}

// Create a fake release a run checks to catch potential breaking changes.
func (r *Release) TestLocalRelease() *ReleaseTest { // release (../../../toolchains/release/tests.go:14:1)
	q := r.query.Select("testLocalRelease")

	return &ReleaseTest{
		query: q,
	}
}

// AsNode returns this Release as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Release) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type ReleaseReport struct { // release (../../../toolchains/release/main.go:23:6)
	query *querybuilder.Selection

	commit   *string
	date     *string
	id       *ID
	markdown *string
	ref      *string
	version  *string
}

func (r *ReleaseReport) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseReport {
	return &ReleaseReport{
		query: q,
	}
}

func (r *ReleaseReport) Artifacts(ctx context.Context) ([]ReleaseReportArtifact, error) { // release (../../../toolchains/release/main.go:30:2)
	q := r.query.Select("artifacts")

	q = q.Select("id")

	type artifacts struct {
		Id ID
	}

	convert := func(fields []artifacts) []ReleaseReportArtifact {
		out := []ReleaseReportArtifact{}

		for i := range fields {
			val := ReleaseReportArtifact{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "ReleaseReportArtifact")
			out = append(out, val)
		}

		return out
	}
	var response []artifacts

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

func (r *ReleaseReport) Commit(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:25:2)
	if r.commit != nil {
		return *r.commit, nil
	}
	q := r.query.Select("commit")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Date(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:28:2)
	if r.date != nil {
		return *r.date, nil
	}
	q := r.query.Select("date")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Errors(ctx context.Context) ([]Error, error) { // release (../../../toolchains/release/main.go:33:2)
	q := r.query.Select("errors")

	q = q.Select("id")

	type errors struct {
		Id ID
	}

	convert := func(fields []errors) []Error {
		out := []Error{}

		for i := range fields {
			val := Error{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "Error")
			out = append(out, val)
		}

		return out
	}
	var response []errors

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

func (r *ReleaseReport) FollowUps(ctx context.Context) ([]ReleaseReportFollowUp, error) { // release (../../../toolchains/release/main.go:31:2)
	q := r.query.Select("followUps")

	q = q.Select("id")

	type followUps struct {
		Id ID
	}

	convert := func(fields []followUps) []ReleaseReportFollowUp {
		out := []ReleaseReportFollowUp{}

		for i := range fields {
			val := ReleaseReportFollowUp{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "ReleaseReportFollowUp")
			out = append(out, val)
		}

		return out
	}
	var response []followUps

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// A unique identifier for this ReleaseReport.
func (r *ReleaseReport) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseReport) XXX_GraphQLType() string {
	return "ReleaseReport"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseReport) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseReport) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseReport) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseReport) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseReport{query: selectNode(dag.query, id, "ReleaseReport")}
	return nil
}

func (r *ReleaseReport) Markdown(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:54:1)
	if r.markdown != nil {
		return *r.markdown, nil
	}
	q := r.query.Select("markdown")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Ref(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:24:2)
	if r.ref != nil {
		return *r.ref, nil
	}
	q := r.query.Select("ref")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Version(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:26:2)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this ReleaseReport as a Node.
// This is a local type conversion — no GraphQL call.
func (r *ReleaseReport) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type ReleaseReportArtifact struct { // release (../../../toolchains/release/main.go:36:6)
	query *querybuilder.Selection

	id   *ID
	link *string
	name *string
	tag  *string
}

func (r *ReleaseReportArtifact) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseReportArtifact {
	return &ReleaseReportArtifact{
		query: q,
	}
}

func (r *ReleaseReportArtifact) Errors(ctx context.Context) ([]Error, error) { // release (../../../toolchains/release/main.go:41:2)
	q := r.query.Select("errors")

	q = q.Select("id")

	type errors struct {
		Id ID
	}

	convert := func(fields []errors) []Error {
		out := []Error{}

		for i := range fields {
			val := Error{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "Error")
			out = append(out, val)
		}

		return out
	}
	var response []errors

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// A unique identifier for this ReleaseReportArtifact.
func (r *ReleaseReportArtifact) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseReportArtifact) XXX_GraphQLType() string {
	return "ReleaseReportArtifact"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseReportArtifact) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseReportArtifact) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseReportArtifact) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseReportArtifact) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseReportArtifact{query: selectNode(dag.query, id, "ReleaseReportArtifact")}
	return nil
}

func (r *ReleaseReportArtifact) Link(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:39:2)
	if r.link != nil {
		return *r.link, nil
	}
	q := r.query.Select("link")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReportArtifact) Name(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:37:2)
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReportArtifact) Tag(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:38:2)
	if r.tag != nil {
		return *r.tag, nil
	}
	q := r.query.Select("tag")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this ReleaseReportArtifact as a Node.
// This is a local type conversion — no GraphQL call.
func (r *ReleaseReportArtifact) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type ReleaseReportFollowUp struct { // release (../../../toolchains/release/main.go:46:6)
	query *querybuilder.Selection

	id   *ID
	link *string
	name *string
}

func (r *ReleaseReportFollowUp) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseReportFollowUp {
	return &ReleaseReportFollowUp{
		query: q,
	}
}

// A unique identifier for this ReleaseReportFollowUp.
func (r *ReleaseReportFollowUp) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseReportFollowUp) XXX_GraphQLType() string {
	return "ReleaseReportFollowUp"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseReportFollowUp) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseReportFollowUp) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseReportFollowUp) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseReportFollowUp) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseReportFollowUp{query: selectNode(dag.query, id, "ReleaseReportFollowUp")}
	return nil
}

func (r *ReleaseReportFollowUp) Link(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:48:2)
	if r.link != nil {
		return *r.link, nil
	}
	q := r.query.Select("link")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReportFollowUp) Name(ctx context.Context) (string, error) { // release (../../../toolchains/release/main.go:47:2)
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this ReleaseReportFollowUp as a Node.
// This is a local type conversion — no GraphQL call.
func (r *ReleaseReportFollowUp) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type ReleaseTest struct { // release (../../../toolchains/release/tests.go:27:6)
	query *querybuilder.Selection

	existingModule *Void
	id             *ID
	newModule      *Void
}

func (r *ReleaseTest) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseTest {
	return &ReleaseTest{
		query: q,
	}
}

func (r *ReleaseTest) Container() *Container { // release (../../../toolchains/release/tests.go:28:2)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// ReleaseTestExistingModuleOpts contains options for ReleaseTest.ExistingModule
type ReleaseTestExistingModuleOpts struct {
	Testdata *Directory // release (../../../toolchains/release/tests.go:55:2)
}

// Test calling an existing module with basic commands.
func (r *ReleaseTest) ExistingModule(ctx context.Context, opts ...ReleaseTestExistingModuleOpts) error { // release (../../../toolchains/release/tests.go:51:1)
	if r.existingModule != nil {
		return nil
	}
	q := r.query.Select("existingModule")
	for i := len(opts) - 1; i >= 0; i-- {
		// `testdata` optional argument
		if !querybuilder.IsZeroValue(opts[i].Testdata) {
			q = q.Arg("testdata", opts[i].Testdata)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this ReleaseTest.
func (r *ReleaseTest) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseTest) XXX_GraphQLType() string {
	return "ReleaseTest"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseTest) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseTest) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseTest) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseTest) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseTest{query: selectNode(dag.query, id, "ReleaseTest")}
	return nil
}

// Test creating a new module and executing basic commands
func (r *ReleaseTest) NewModule(ctx context.Context) error { // release (../../../toolchains/release/tests.go:33:1)
	if r.newModule != nil {
		return nil
	}
	q := r.query.Select("newModule")

	return q.Execute(ctx)
}

// AsNode returns this ReleaseTest as a Node.
// This is a local type conversion — no GraphQL call.
func (r *ReleaseTest) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
