// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"dagger/docs/internal/dagger/core"
)

type EngineDev = core.EngineDev

type WithEngineDevFunc = core.WithEngineDevFunc

// EngineDevContainerOpts contains options for EngineDev.Container
type EngineDevContainerOpts = core.EngineDevContainerOpts

// EngineDevGraphqlSchemaOpts contains options for EngineDev.GraphqlSchema
type EngineDevGraphqlSchemaOpts = core.EngineDevGraphqlSchemaOpts

// EngineDevInstallClientOpts contains options for EngineDev.InstallClient
type EngineDevInstallClientOpts = core.EngineDevInstallClientOpts

// EngineDevLoadToDockerOpts contains options for EngineDev.LoadToDocker
type EngineDevLoadToDockerOpts = core.EngineDevLoadToDockerOpts

// EngineDevPublishOpts contains options for EngineDev.Publish
type EngineDevPublishOpts = core.EngineDevPublishOpts

// EngineDevServiceOpts contains options for EngineDev.Service
type EngineDevServiceOpts = core.EngineDevServiceOpts

// EngineDevTestOpts contains options for EngineDev.Test
type EngineDevTestOpts = core.EngineDevTestOpts

// EngineDevTestProfileOpts contains options for EngineDev.TestProfile
type EngineDevTestProfileOpts = core.EngineDevTestProfileOpts

// EngineDevTestTelemetryOpts contains options for EngineDev.TestTelemetry
type EngineDevTestTelemetryOpts = core.EngineDevTestTelemetryOpts

type EngineDevLoadedEngine = core.EngineDevLoadedEngine

// EngineDevLoadedEngineStartOpts contains options for EngineDevLoadedEngine.Start
type EngineDevLoadedEngineStartOpts = core.EngineDevLoadedEngineStartOpts

// The result of a profiled test run: the test engine's wcprof recording, and
// how the tests went.
type EngineDevTestProfileResult = core.EngineDevTestProfileResult

// EngineDevOpts contains options for Query.EngineDev
type EngineDevOpts = core.EngineDevOpts
