name = "mcp-lab"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "cli-dev"
  source = "../cli-dev"

[[dependencies]]
  name = "engine-dev"
  source = "../engine-dev"
