pipeline {
  agent { label 'dagger' }

  stages {
    stage("dagger") {
      steps {
        sh '''
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install dagger-io
            python main.py
        '''
      }
    }
  }
}
