// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/viztest/internal/dagger"
	"dagger/viztest/internal/querybuilder"
	"dagger/viztest/internal/telemetry"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Viztest) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Num int
	}
	concrete.Num = r.Num
	return json.Marshal(&concrete)
}

func (r *Viztest) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Num int
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Num = concrete.Num
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Viztest":
		switch fnName {
		case "Accounting":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).Accounting(&parent), nil
		case "Add":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var diff int
			if inputArgs["diff"] != nil {
				err = json.Unmarshal([]byte(inputArgs["diff"]), &diff)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg diff", err))
				}
			}
			return (*Viztest).Add(&parent, diff), nil
		case "CachedExecService":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).CachedExecService(&parent), nil
		case "CachedExecs":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).CachedExecs(&parent, ctx)
		case "CallBubblingDep":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).CallBubblingDep(&parent, ctx)
		case "CallFailingDep":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).CallFailingDep(&parent, ctx)
		case "Colors16":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).Colors16(&parent, ctx)
		case "Colors256":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).Colors256(&parent, ctx)
		case "CountFiles":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var dir *dagger.Directory
			if inputArgs["dir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dir"]), &dir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dir", err))
				}
			}
			return (*Viztest).CountFiles(&parent, ctx, dir)
		case "CustomSpan":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).CustomSpan(&parent, ctx)
		case "DeepSleep":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).DeepSleep(&parent), nil
		case "DiskMetrics":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).DiskMetrics(&parent, ctx)
		case "DockerBuild":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).DockerBuild(&parent), nil
		case "DockerBuildCached":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).DockerBuildCached(&parent), nil
		case "DockerBuildFail":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).DockerBuildFail(&parent), nil
		case "Echo":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var message string
			if inputArgs["message"] != nil {
				err = json.Unmarshal([]byte(inputArgs["message"]), &message)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg message", err))
				}
			}
			return (*Viztest).Echo(&parent, ctx, message)
		case "Encapsulate":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).Encapsulate(&parent, ctx)
		case "ExecService":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).ExecService(&parent), nil
		case "FailEffect":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).FailEffect(&parent), nil
		case "FailEncapsulated":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).FailEncapsulated(&parent, ctx)
		case "FailLog":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).FailLog(&parent, ctx)
		case "FailLogNative":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).FailLogNative(&parent, ctx)
		case "FailMulti":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).FailMulti(&parent, ctx)
		case "FailSlow":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var after string
			if inputArgs["after"] != nil {
				err = json.Unmarshal([]byte(inputArgs["after"]), &after)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg after", err))
				}
			}
			return nil, (*Viztest).FailSlow(&parent, ctx, after)
		case "GitReadme":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var remote string
			if inputArgs["remote"] != nil {
				err = json.Unmarshal([]byte(inputArgs["remote"]), &remote)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg remote", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return (*Viztest).GitReadme(&parent, ctx, remote, version)
		case "HTTPReadme":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var remote string
			if inputArgs["remote"] != nil {
				err = json.Unmarshal([]byte(inputArgs["remote"]), &remote)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg remote", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			return (*Viztest).HTTPReadme(&parent, ctx, remote, version)
		case "HelloWorld":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).HelloWorld(&parent), nil
		case "List":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var dir *dagger.Directory
			if inputArgs["dir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dir"]), &dir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dir", err))
				}
			}
			return (*Viztest).List(&parent, ctx, dir)
		case "LogStderr":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			(*Viztest).LogStderr(&parent)
			return nil, nil
		case "LogStdout":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			(*Viztest).LogStdout(&parent)
			return nil, nil
		case "LogWithChildren":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).LogWithChildren(&parent, ctx), nil
		case "ManyLines":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			(*Viztest).ManyLines(&parent, n)
			return nil, nil
		case "ManySpans":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			var delayMs int
			if inputArgs["delayMs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["delayMs"]), &delayMs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg delayMs", err))
				}
			}
			(*Viztest).ManySpans(&parent, ctx, n, delayMs)
			return nil, nil
		case "NestedCalls":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).NestedCalls(&parent, ctx)
		case "NoExecService":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).NoExecService(&parent), nil
		case "ObjectLists":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).ObjectLists(&parent, ctx)
		case "PathArgs":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var file *dagger.File
			if inputArgs["file"] != nil {
				err = json.Unmarshal([]byte(inputArgs["file"]), &file)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg file", err))
				}
			}
			var dir *dagger.Directory
			if inputArgs["dir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dir"]), &dir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dir", err))
				}
			}
			var contextFile *dagger.File
			if inputArgs["contextFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["contextFile"]), &contextFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg contextFile", err))
				}
			}
			var contextDir *dagger.Directory
			if inputArgs["contextDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["contextDir"]), &contextDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg contextDir", err))
				}
			}
			return nil, (*Viztest).PathArgs(&parent, ctx, file, dir, contextFile, contextDir)
		case "Pending":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).Pending(&parent, ctx)
		case "PrimaryLines":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			return (*Viztest).PrimaryLines(&parent, n), nil
		case "RevealAndLog":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).RevealAndLog(&parent, ctx)
		case "RevealedSpans":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).RevealedSpans(&parent, ctx)
		case "SameDiffClients":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var message string
			if inputArgs["message"] != nil {
				err = json.Unmarshal([]byte(inputArgs["message"]), &message)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg message", err))
				}
			}
			return (*Viztest).SameDiffClients(&parent, ctx, message)
		case "Spam":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).Spam(&parent), nil
		case "StreamingChunks":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var batchSize int
			if inputArgs["batchSize"] != nil {
				err = json.Unmarshal([]byte(inputArgs["batchSize"]), &batchSize)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg batchSize", err))
				}
			}
			var delayMs int
			if inputArgs["delayMs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["delayMs"]), &delayMs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg delayMs", err))
				}
			}
			(*Viztest).StreamingChunks(&parent, ctx, batchSize, delayMs)
			return nil, nil
		case "StreamingLogs":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var batchSize int
			if inputArgs["batchSize"] != nil {
				err = json.Unmarshal([]byte(inputArgs["batchSize"]), &batchSize)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg batchSize", err))
				}
			}
			var delayMs int
			if inputArgs["delayMs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["delayMs"]), &delayMs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg delayMs", err))
				}
			}
			(*Viztest).StreamingLogs(&parent, ctx, batchSize, delayMs)
			return nil, nil
		case "Terminal":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).Terminal(&parent), nil
		case "TraceFunctionCalls":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).TraceFunctionCalls(&parent, ctx)
		case "TraceRemoteFunctionCalls":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).TraceRemoteFunctionCalls(&parent, ctx)
		case "Uppercase":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var message string
			if inputArgs["message"] != nil {
				err = json.Unmarshal([]byte(inputArgs["message"]), &message)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg message", err))
				}
			}
			return (*Viztest).Uppercase(&parent, ctx, message)
		case "UseCachedExecService":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).UseCachedExecService(&parent, ctx)
		case "UseExecService":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Viztest).UseExecService(&parent, ctx)
		case "UseNoExecService":
			var parent Viztest
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Viztest).UseNoExecService(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
