name = "git-releaser"
engineVersion = "v0.21.9"

[runtime]
  source = "go"

[[dependencies]]
  name = "alpine"
  source = "https://github.com/dagger/alpine@main"
  pin = "0cbccf6115c57069e2aa3ef9b07133093f1a3246"

[codegen]
  automaticGitignore = false
