// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `NestedDepID` scalar type represents an identifier for an object of type NestedDep.
type NestedDepID string // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)

// Retrieve the binding value, as type NestedDep
func (r *Binding) AsNestedDep() *NestedDep { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)
	q := r.query.Select("asNestedDep")

	return &NestedDep{
		query: q,
	}
}

// Create or update a binding of type NestedDep in the environment
func (r *Env) WithNestedDepInput(name string, value *NestedDep, description string) *Env { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)
	assertNotNil("value", value)
	q := r.query.Select("withNestedDepInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired NestedDep output to be assigned in the environment
func (r *Env) WithNestedDepOutput(name string, description string) *Env { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)
	q := r.query.Select("withNestedDepOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type NestedDep struct { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)
	query *querybuilder.Selection

	failingFunction *Void
	id              *NestedDepID
}

func (r *NestedDep) WithGraphQLQuery(q *querybuilder.Selection) *NestedDep {
	return &NestedDep{
		query: q,
	}
}

func (r *NestedDep) FailingFunction(ctx context.Context) error { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:10:1)
	if r.failingFunction != nil {
		return nil
	}
	q := r.query.Select("failingFunction")

	return q.Execute(ctx)
}

// A unique identifier for this NestedDep.
func (r *NestedDep) ID(ctx context.Context) (NestedDepID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response NestedDepID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *NestedDep) XXX_GraphQLType() string {
	return "NestedDep"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *NestedDep) XXX_GraphQLIDType() string {
	return "NestedDepID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *NestedDep) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *NestedDep) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *NestedDep) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadNestedDepFromID(NestedDepID(id))
	return nil
}

// Load a NestedDep from its ID.
func (r *Query) LoadNestedDepFromID(id NestedDepID) *NestedDep { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)
	q := r.query.Select("loadNestedDepFromID")
	q = q.Arg("id", id)

	return &NestedDep{
		query: q,
	}
}

func (r *Query) NestedDep() *NestedDep { // nested-dep (../../../../../../dagql/idtui/viztest/dep/nested-dep/main.go:8:6)
	q := r.query.Select("nestedDep")

	return &NestedDep{
		query: q,
	}
}
