#!/usr/bin/env bash

set -e -u -x

DAGGER_SRC_ROOT="$(cd $(dirname $(realpath "${BASH_SOURCE[0]}"))/.. && pwd)"
MAGEDIR="$DAGGER_SRC_ROOT/ci/mage"

cd "$MAGEDIR"

exec go run main.go -w "$DAGGER_SRC_ROOT" "$@"