#!/usr/bin/env bash

set -e -u

export DAGGER_SRC_ROOT="$(cd $(dirname $(realpath "${BASH_SOURCE[0]}"))/.. && pwd)"
export MAGEDIR="$DAGGER_SRC_ROOT/.dagger/mage"

pushd $MAGEDIR > /dev/null
eval $(go run main.go -w $DAGGER_SRC_ROOT engine:devenv)
popd > /dev/null

export PATH=$DAGGER_SRC_ROOT/bin:$PATH
exec "$@"
