// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/php-sdk-dev/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r PhpSdkDev) MarshalJSON() ([]byte, error) {
	var concrete struct {
		OriginalWorkspace  *dagger.Directory
		Workspace          *dagger.Directory
		DoctumConfigPath   string
		SourcePath         string
		ClientDockerConfig *dagger.Secret
		Ws                 *dagger.Workspace
	}
	concrete.OriginalWorkspace = r.OriginalWorkspace
	concrete.Workspace = r.Workspace
	concrete.DoctumConfigPath = r.DoctumConfigPath
	concrete.SourcePath = r.SourcePath
	concrete.ClientDockerConfig = r.ClientDockerConfig
	concrete.Ws = r.Ws
	return json.Marshal(&concrete)
}

func (r *PhpSdkDev) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		OriginalWorkspace  *dagger.Directory
		Workspace          *dagger.Directory
		DoctumConfigPath   string
		SourcePath         string
		ClientDockerConfig *dagger.Secret
		Ws                 *dagger.Workspace
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.OriginalWorkspace = concrete.OriginalWorkspace
	r.Workspace = concrete.Workspace
	r.DoctumConfigPath = concrete.DoctumConfigPath
	r.SourcePath = concrete.SourcePath
	r.ClientDockerConfig = concrete.ClientDockerConfig
	r.Ws = concrete.Ws
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "PhpSdkDev":
		switch fnName {
		case "API":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).API(&parent, ctx)
		case "BaseContainer":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).BaseContainer(&parent), nil
		case "Changes":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).Changes(&parent), nil
		case "DevContainer":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var runInstall bool
			if inputArgs["runInstall"] != nil {
				err = json.Unmarshal([]byte(inputArgs["runInstall"]), &runInstall)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg runInstall", err))
				}
			}
			return (*PhpSdkDev).DevContainer(&parent, runInstall), nil
		case "DoctumConfig":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).DoctumConfig(&parent), nil
		case "PhpCodeSniffer":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*PhpSdkDev).PhpCodeSniffer(&parent, ctx)
		case "PhpStan":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*PhpSdkDev).PhpStan(&parent, ctx)
		case "Release":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceRepo *dagger.GitRepository
			if inputArgs["sourceRepo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceRepo"]), &sourceRepo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceRepo", err))
				}
			}
			var sourceTag string
			if inputArgs["sourceTag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceTag"]), &sourceTag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceTag", err))
				}
			}
			var dest string
			if inputArgs["dest"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dest"]), &dest)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dest", err))
				}
			}
			var githubToken *dagger.Secret
			if inputArgs["githubToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["githubToken"]), &githubToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg githubToken", err))
				}
			}
			return nil, (*PhpSdkDev).Release(&parent, ctx, sourceRepo, sourceTag, dest, githubToken)
		case "ReleaseDryRun":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceRepo *dagger.GitRepository
			if inputArgs["sourceRepo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceRepo"]), &sourceRepo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceRepo", err))
				}
			}
			var sourceTag string
			if inputArgs["sourceTag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceTag"]), &sourceTag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceTag", err))
				}
			}
			var destRemote string
			if inputArgs["destRemote"] != nil {
				err = json.Unmarshal([]byte(inputArgs["destRemote"]), &destRemote)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg destRemote", err))
				}
			}
			return nil, (*PhpSdkDev).ReleaseDryRun(&parent, ctx, sourceRepo, sourceTag, destRemote)
		case "Source":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).Source(&parent), nil
		case "Test":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*PhpSdkDev).Test(&parent, ctx)
		case "VersionFromTag":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			return (*PhpSdkDev).VersionFromTag(&parent, tag), nil
		case "WithGeneratedClient":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).WithGeneratedClient(&parent), nil
		case "WithGeneratedDocs":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PhpSdkDev).WithGeneratedDocs(&parent, ctx)
		case "":
			var parent PhpSdkDev
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var workspaceDir *dagger.Directory
			if inputArgs["workspaceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["workspaceDir"]), &workspaceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg workspaceDir", err))
				}
			}
			var sourcePath string
			if inputArgs["sourcePath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourcePath"]), &sourcePath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourcePath", err))
				}
			}
			var doctumConfigPath string
			if inputArgs["doctumConfigPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["doctumConfigPath"]), &doctumConfigPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg doctumConfigPath", err))
				}
			}
			var clientDockerConfig *dagger.Secret
			if inputArgs["clientDockerConfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["clientDockerConfig"]), &clientDockerConfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg clientDockerConfig", err))
				}
			}
			var ws *dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			return New(workspaceDir, sourcePath, doctumConfigPath, clientDockerConfig, ws), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("Toolchain to develop the Dagger PHP SDK (experimental)\n").
			WithObject(
				dag.TypeDef().WithObject("PhpSdkDev", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 23, 6)}).
					WithFunction(
						dag.Function("API",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("Regenerate the PHP SDK API").
							WithSourceMap(dag.SourceMap("main.go", 151, 1)).
							WithGenerator()).
					WithFunction(
						dag.Function("BaseContainer",
							dag.TypeDef().WithObject("Container")).
							WithSourceMap(dag.SourceMap("main.go", 61, 1))).
					WithFunction(
						dag.Function("Changes",
							dag.TypeDef().WithObject("Changeset")).
							WithSourceMap(dag.SourceMap("main.go", 162, 1))).
					WithFunction(
						dag.Function("DevContainer",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Returns the PHP SDK workspace mounted in a dev container,\nand working directory set to the SDK source").
							WithSourceMap(dag.SourceMap("main.go", 89, 1)).
							WithArg("runInstall", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind), dagger.FunctionWithArgOpts{Description: "Run composer install before returning the container", SourceMap: dag.SourceMap("main.go", 92, 2), DefaultValue: dagger.JSON("\"false\"")})).
					WithFunction(
						dag.Function("DoctumConfig",
							dag.TypeDef().WithObject("File")).
							WithDescription("DoctumConfig returns the doctum configuration file").
							WithSourceMap(dag.SourceMap("main.go", 115, 1))).
					WithFunction(
						dag.Function("PhpCodeSniffer",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Lint the PHP code with PHP CodeSniffer (https://github.com/squizlabs/PHP_CodeSniffer)").
							WithSourceMap(dag.SourceMap("main.go", 121, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("PhpStan",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Analyze the PHP code with PHPStan (https://phpstan.org)").
							WithSourceMap(dag.SourceMap("main.go", 131, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("Release",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Publish the PHP SDK").
							WithSourceMap(dag.SourceMap("main.go", 246, 1)).
							WithArg("sourceRepo", dag.TypeDef().WithObject("GitRepository").WithOptional(true), dagger.FunctionWithArgOpts{Description: "The source git repository to release", SourceMap: dag.SourceMap("main.go", 251, 2), DefaultPath: "/"}).
							WithArg("sourceTag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "The source git tag to release", SourceMap: dag.SourceMap("main.go", 254, 2)}).
							WithArg("dest", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 258, 2), DefaultValue: dagger.JSON("\"https://github.com/dagger/dagger-php-sdk.git\"")}).
							WithArg("githubToken", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 260, 2)})).
					WithFunction(
						dag.Function("ReleaseDryRun",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Test the publishing process").
							WithSourceMap(dag.SourceMap("main.go", 215, 1)).
							WithArg("sourceRepo", dag.TypeDef().WithObject("GitRepository").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Source git repository to fake-release", SourceMap: dag.SourceMap("main.go", 219, 2), DefaultPath: "/"}).
							WithArg("sourceTag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Source git tag to fake-release", SourceMap: dag.SourceMap("main.go", 222, 2), DefaultValue: dagger.JSON("\"HEAD\"")}).
							WithArg("destRemote", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Target git remote to fake-release *to*", SourceMap: dag.SourceMap("main.go", 225, 2), DefaultValue: dagger.JSON("\"https://github.com/dagger/dagger-php-sdk.git\"")})).
					WithFunction(
						dag.Function("Source",
							dag.TypeDef().WithObject("Directory")).
							WithDescription("Source returns the source directory for the PHP SDK").
							WithSourceMap(dag.SourceMap("main.go", 110, 1))).
					WithFunction(
						dag.Function("Test",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Test the PHP SDK with PHPUnit (https://phpunit.de/)").
							WithSourceMap(dag.SourceMap("main.go", 142, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("VersionFromTag",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Get v1.2.3 from sdk/php/v1.2.3").
							WithSourceMap(dag.SourceMap("main.go", 240, 1)).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 240, 35)})).
					WithFunction(
						dag.Function("WithGeneratedClient",
							dag.TypeDef().WithObject("PhpSdkDev")).
							WithSourceMap(dag.SourceMap("main.go", 166, 1))).
					WithFunction(
						dag.Function("WithGeneratedDocs",
							dag.TypeDef().WithObject("PhpSdkDev")).
							WithDescription("Generate reference docs from the generated client\nNOTE: it's the caller's responsibility to ensure the generated client is up-to-date\n(see WithGeneratedClient)").
							WithSourceMap(dag.SourceMap("main.go", 186, 1))).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("PhpSdkDev")).
							WithDescription("Develop the Dagger PHP SDK (experimental)").
							WithSourceMap(dag.SourceMap("main.go", 33, 1)).
							WithArg("workspaceDir", dag.TypeDef().WithObject("Directory").WithOptional(true), dagger.FunctionWithArgOpts{Description: "A directory with all the files needed to develop the SDK", SourceMap: dag.SourceMap("main.go", 37, 2), DefaultPath: "/", Ignore: []string{"*", "!sdk/php", "!docs/doctum-config.php", "!docs/static/reference/php", "sdk/php/.changes"}}).
							WithArg("sourcePath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "The path of the SDK source in the workspace", SourceMap: dag.SourceMap("main.go", 40, 2), DefaultValue: dagger.JSON("\"sdk/php\"")}).
							WithArg("doctumConfigPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "The path of the doctum config in the workspace", SourceMap: dag.SourceMap("main.go", 43, 2), DefaultValue: dagger.JSON("\"docs/doctum-config.php\"")}).
							WithArg("clientDockerConfig", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "A docker config file with credentials to install on clients.", SourceMap: dag.SourceMap("main.go", 46, 2)}).
							WithArg("ws", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{Description: "Workspace forwarded to engine-dev for VCS stamping. Auto-injected on a\ndirect call; dependencies don't inherit it, so callers must forward it.", SourceMap: dag.SourceMap("main.go", 49, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
