[package]
name = "dagger-bootstrap"
description = "A bootstrapper for orchestrating codegen for the rust sdk"
publish = false
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "dagger-rust"
path = "src/main.rs"

[dependencies]
dagger-codegen = { workspace = true }
dagger-sdk-completeness = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tempfile.workspace = true
clap.workspace = true
fs4.workspace = true
sha2.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
proptest.workspace = true
