name = "python-sdk-dev"
engineVersion = "v0.21.7"
include = ["../../go.sum", "../../go.mod", "../../util/parallel", "../../util/dockerfileextractor", "../../sdk/python/runtime/images"]

[runtime]
  source = "go"

[[dependencies]]
  name = "dagger-engine"
  source = "../engine-dev"

[[dependencies]]
  name = "dockerd"
  source = "dockerd"

[[dependencies]]
  name = "pytest"
  source = "github.com/dagger/pytest@main"
  pin = "cdf6dc0bce0fe8fdf87c6b26ecd991e6f96200b0"

[[dependencies]]
  name = "wolfi"
  source = "../../modules/wolfi"

[codegen]
  automaticGitignore = false
