// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Codegen struct { // codegen (../../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *Codegen) WithGraphQLQuery(q *querybuilder.Selection) *Codegen {
	return &Codegen{
		query: q,
	}
}

func (r *Codegen) Binary() *File { // codegen (../../../../:0:0)
	q := r.query.Select("binary")

	return &File{
		query: q,
	}
}

// A unique identifier for this Codegen.
func (r *Codegen) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Codegen) XXX_GraphQLType() string {
	return "Codegen"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Codegen) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Codegen) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Codegen) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Codegen) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Codegen{query: selectNode(dag.query, id, "Codegen")}
	return nil
}

func (r *Codegen) Source() *Directory { // codegen (../../../../:0:0)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// AsNode returns this Codegen as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Codegen) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// CodegenOpts contains options for Query.Codegen
type CodegenOpts struct {
	Source *Directory // codegen (../../../../:0:0)

	Ws *Workspace // codegen (../../../../:0:0)
}

func (r *Query) Codegen(opts ...CodegenOpts) *Codegen { // codegen (../../../../:0:0)
	q := r.query.Select("codegen")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return &Codegen{
		query: q,
	}
}
