// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"dagger/python-client-dev/internal/dagger/core"
)

type Pytest = core.Pytest

// PytestTestOpts contains options for Pytest.Test
type PytestTestOpts = core.PytestTestOpts

// PytestOpts contains options for Query.Pytest
type PytestOpts = core.PytestOpts
