[package]
name = "dagger-sdk-completeness"
description = "Internal completeness contract for the Dagger Rust SDK"
publish = false

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dagger-codegen.workspace = true
dagger-sdk-engine.workspace = true
clap.workspace = true
rand.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true

[dev-dependencies]
dagger-sdk = { workspace = true, default-features = false }
pretty_assertions.workspace = true
proptest.workspace = true
tempfile.workspace = true
