pipeline {
  agent { label 'dagger' }

  // assumes that the Dagger Cloud token
  // is in a Jenkins credential named DAGGER_CLOUD_TOKEN
  environment {
    DAGGER_CLOUD_TOKEN =  credentials('DAGGER_CLOUD_TOKEN')
  }

  stages {
    stage("dagger") {
      steps {
        sh '''
            curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=bin sh
            bin/dagger call -m github.com/shykes/hello hello --greeting "bonjour" --name "from jenkins"
        '''
      }
    }
  }
}
