// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// A unique identifier for an object.
type SuperDashDashID = ID // super-dash-dash (../../../../../../../../../:0:0)

// SuperDashDashOpts contains options for Query.SuperDashDash
type SuperDashDashOpts struct {

	// Default: "hello"
	Greeting string

	Dir *Directory

	Password *Secret

	File *File
}

func (r *Query) SuperDashDash(opts ...SuperDashDashOpts) *SuperDashDash { // super-dash-dash (../../../../../../../../../:0:0)
	q := r.query.Select("superDashDash")
	for i := len(opts) - 1; i >= 0; i-- {
		// `greeting` optional argument
		if !querybuilder.IsZeroValue(opts[i].Greeting) {
			q = q.Arg("greeting", opts[i].Greeting)
		}
		// `dir` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dir) {
			q = q.Arg("dir", opts[i].Dir)
		}
		// `password` optional argument
		if !querybuilder.IsZeroValue(opts[i].Password) {
			q = q.Arg("password", opts[i].Password)
		}
		// `file` optional argument
		if !querybuilder.IsZeroValue(opts[i].File) {
			q = q.Arg("file", opts[i].File)
		}
	}

	return &SuperDashDash{
		query: q,
	}
}

type SuperDashDash struct { // super-dash-dash (../../../../../../../../../:0:0)
	query *querybuilder.Selection

	capitalize *string
	greeting   *string
	id         *SuperDashDashID
	message    *string
}

func (r *SuperDashDash) WithGraphQLQuery(q *querybuilder.Selection) *SuperDashDash {
	return &SuperDashDash{
		query: q,
	}
}

// Capitalize a string
func (r *SuperDashDash) Capitalize(ctx context.Context, s string) (string, error) {
	if r.capitalize != nil {
		return *r.capitalize, nil
	}
	q := r.query.Select("capitalize")
	q = q.Arg("s", s)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *SuperDashDash) Dir() *Directory {
	q := r.query.Select("dir")

	return &Directory{
		query: q,
	}
}

func (r *SuperDashDash) File() *File {
	q := r.query.Select("file")

	return &File{
		query: q,
	}
}

func (r *SuperDashDash) Greeting(ctx context.Context) (string, error) {
	if r.greeting != nil {
		return *r.greeting, nil
	}
	q := r.query.Select("greeting")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this SuperDashDash.
func (r *SuperDashDash) ID(ctx context.Context) (SuperDashDashID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response SuperDashDashID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *SuperDashDash) XXX_GraphQLType() string {
	return "SuperDashDash"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *SuperDashDash) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *SuperDashDash) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *SuperDashDash) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *SuperDashDash) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = SuperDashDash{query: selectNode(dag.query, id, "SuperDashDash")}
	return nil
}

// List the contents of a directory
func (r *SuperDashDash) Ls(ctx context.Context, dir *Directory) ([]string, error) {
	assertNotNil("dir", dir)
	q := r.query.Select("ls")
	q = q.Arg("dir", dir)

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// SuperDashDashMessageOpts contains options for SuperDashDash.Message
type SuperDashDashMessageOpts struct {

	// Default: "world"
	Name string
}

func (r *SuperDashDash) Message(ctx context.Context, opts ...SuperDashDashMessageOpts) (string, error) {
	if r.message != nil {
		return *r.message, nil
	}
	q := r.query.Select("message")
	for i := len(opts) - 1; i >= 0; i-- {
		// `name` optional argument
		if !querybuilder.IsZeroValue(opts[i].Name) {
			q = q.Arg("name", opts[i].Name)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *SuperDashDash) Password() *Secret {
	q := r.query.Select("password")

	return &Secret{
		query: q,
	}
}
