// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `ApkoBuildResultID` scalar type represents an identifier for an object of type ApkoBuildResult.
type ApkoBuildResultID string // apko (../../../../../toolchains/release/apko/main.go:251:6)

// The `ApkoConfigID` scalar type represents an identifier for an object of type ApkoConfig.
type ApkoConfigID string // apko (../../../../../toolchains/release/apko/config.go:31:6)

// The `ApkoID` scalar type represents an identifier for an object of type Apko.
type ApkoID string // apko (../../../../../toolchains/release/apko/main.go:16:6)

type Apko struct { // apko (../../../../../toolchains/release/apko/main.go:16:6)
	query *querybuilder.Selection

	id      *ApkoID
	publish *Void
}
type WithApkoFunc func(r *Apko) *Apko

// With calls the provided function with current Apko.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Apko) With(f WithApkoFunc) *Apko {
	return f(r)
}

func (r *Apko) WithGraphQLQuery(q *querybuilder.Selection) *Apko {
	return &Apko{
		query: q,
	}
}

// Load the Alpine base configuration.
func (r *Apko) Alpine() *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:11:1)
	q := r.query.Select("alpine")

	return &ApkoConfig{
		query: q,
	}
}

// ApkoBuildOpts contains options for Apko.Build
type ApkoBuildOpts struct {
	//
	// A .lock.json file (e.g. produced by apko lock) that constraints versions of packages to the listed ones.
	//
	Lockfile *File // apko (../../../../../toolchains/release/apko/main.go:172:2)
	//
	// OCI annotations to add. Separate with colon (key:value).
	//
	Annotations []string // apko (../../../../../toolchains/release/apko/main.go:177:2)
	//
	// Architectures to build for (e.g., x86_64,ppc64le,arm64) -- default is all, unless specified in config. Can also use 'host' to indicate arch of host this is running on.
	//
	Arch []string // apko (../../../../../toolchains/release/apko/main.go:182:2)
	//
	// Date used for the timestamps of the files inside the image in RFC3339 format.
	//
	BuildDate string // apko (../../../../../toolchains/release/apko/main.go:187:2)
	//
	// Path to extra keys to include in the keyring.
	//
	KeyringAppend []string // apko (../../../../../toolchains/release/apko/main.go:192:2)
	//
	// Do not use network to fetch packages (cache must be pre-populated).
	//
	Offline bool // apko (../../../../../toolchains/release/apko/main.go:197:2)
	//
	// Extra packages to include.
	//
	PackageAppend []string // apko (../../../../../toolchains/release/apko/main.go:202:2)
	//
	// Path to extra repositories to include.
	//
	RepositoryAppend []string // apko (../../../../../toolchains/release/apko/main.go:207:2)
	//
	// Detect and embed VCS URLs.
	//
	//
	// Default: true
	Vcs bool // apko (../../../../../toolchains/release/apko/main.go:215:2)
}

// Build an image from a YAML configuration file.
func (r *Apko) Build(config *File, tag string, opts ...ApkoBuildOpts) *ApkoBuildResult { // apko (../../../../../toolchains/release/apko/main.go:162:1)
	assertNotNil("config", config)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `lockfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Lockfile) {
			q = q.Arg("lockfile", opts[i].Lockfile)
		}
		// `annotations` optional argument
		if !querybuilder.IsZeroValue(opts[i].Annotations) {
			q = q.Arg("annotations", opts[i].Annotations)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `buildDate` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildDate) {
			q = q.Arg("buildDate", opts[i].BuildDate)
		}
		// `keyringAppend` optional argument
		if !querybuilder.IsZeroValue(opts[i].KeyringAppend) {
			q = q.Arg("keyringAppend", opts[i].KeyringAppend)
		}
		// `offline` optional argument
		if !querybuilder.IsZeroValue(opts[i].Offline) {
			q = q.Arg("offline", opts[i].Offline)
		}
		// `packageAppend` optional argument
		if !querybuilder.IsZeroValue(opts[i].PackageAppend) {
			q = q.Arg("packageAppend", opts[i].PackageAppend)
		}
		// `repositoryAppend` optional argument
		if !querybuilder.IsZeroValue(opts[i].RepositoryAppend) {
			q = q.Arg("repositoryAppend", opts[i].RepositoryAppend)
		}
		// `vcs` optional argument
		if !querybuilder.IsZeroValue(opts[i].Vcs) {
			q = q.Arg("vcs", opts[i].Vcs)
		}
	}
	q = q.Arg("config", config)
	q = q.Arg("tag", tag)

	return &ApkoBuildResult{
		query: q,
	}
}

// Load a configuration file.
func (r *Apko) Config(file *File) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:24:1)
	assertNotNil("file", file)
	q := r.query.Select("config")
	q = q.Arg("file", file)

	return &ApkoConfig{
		query: q,
	}
}

// A unique identifier for this Apko.
func (r *Apko) ID(ctx context.Context) (ApkoID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ApkoID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Apko) XXX_GraphQLType() string {
	return "Apko"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Apko) XXX_GraphQLIDType() string {
	return "ApkoID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Apko) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Apko) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Apko) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadApkoFromID(ApkoID(id))
	return nil
}

// Load a configuration preset.
func (r *Apko) Preset(name string) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:16:1)
	q := r.query.Select("preset")
	q = q.Arg("name", name)

	return &ApkoConfig{
		query: q,
	}
}

// ApkoPublishOpts contains options for Apko.Publish
type ApkoPublishOpts struct {
	//
	// OCI annotations to add. Separate with colon (key:value).
	//
	Annotations []string // apko (../../../../../toolchains/release/apko/main.go:274:2)
	//
	// Architectures to build for (e.g., x86_64,ppc64le,arm64) -- default is all, unless specified in config. Can also use 'host' to indicate arch of host this is running on.
	//
	Arch []string // apko (../../../../../toolchains/release/apko/main.go:279:2)
	//
	// Date used for the timestamps of the files inside the image in RFC3339 format.
	//
	BuildDate string // apko (../../../../../toolchains/release/apko/main.go:284:2)
	//
	// Path to extra keys to include in the keyring.
	//
	KeyringAppend []string // apko (../../../../../toolchains/release/apko/main.go:289:2)
	//
	// Do not use network to fetch packages (cache must be pre-populated).
	//
	Offline bool // apko (../../../../../toolchains/release/apko/main.go:294:2)
	//
	// Extra packages to include.
	//
	PackageAppend []string // apko (../../../../../toolchains/release/apko/main.go:299:2)
	//
	// Path to extra repositories to include.
	//
	RepositoryAppend []string // apko (../../../../../toolchains/release/apko/main.go:304:2)
	//
	// Detect and embed VCS URLs.
	//
	//
	// Default: true
	Vcs bool // apko (../../../../../toolchains/release/apko/main.go:312:2)
}

// Publish a built image from a YAML configuration file.
func (r *Apko) Publish(ctx context.Context, config *File, tag string, opts ...ApkoPublishOpts) error { // apko (../../../../../toolchains/release/apko/main.go:262:1)
	assertNotNil("config", config)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `annotations` optional argument
		if !querybuilder.IsZeroValue(opts[i].Annotations) {
			q = q.Arg("annotations", opts[i].Annotations)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `buildDate` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildDate) {
			q = q.Arg("buildDate", opts[i].BuildDate)
		}
		// `keyringAppend` optional argument
		if !querybuilder.IsZeroValue(opts[i].KeyringAppend) {
			q = q.Arg("keyringAppend", opts[i].KeyringAppend)
		}
		// `offline` optional argument
		if !querybuilder.IsZeroValue(opts[i].Offline) {
			q = q.Arg("offline", opts[i].Offline)
		}
		// `packageAppend` optional argument
		if !querybuilder.IsZeroValue(opts[i].PackageAppend) {
			q = q.Arg("packageAppend", opts[i].PackageAppend)
		}
		// `repositoryAppend` optional argument
		if !querybuilder.IsZeroValue(opts[i].RepositoryAppend) {
			q = q.Arg("repositoryAppend", opts[i].RepositoryAppend)
		}
		// `vcs` optional argument
		if !querybuilder.IsZeroValue(opts[i].Vcs) {
			q = q.Arg("vcs", opts[i].Vcs)
		}
	}
	q = q.Arg("config", config)
	q = q.Arg("tag", tag)

	return q.Execute(ctx)
}

// ApkoWithCacheOpts contains options for Apko.WithCache
type ApkoWithCacheOpts struct {
	//
	// Identifier of the directory to use as the cache volume's root.
	//
	Source *Directory // apko (../../../../../toolchains/release/apko/main.go:67:2)
	//
	// Sharing mode of the cache volume.
	//
	Sharing CacheSharingMode // apko (../../../../../toolchains/release/apko/main.go:72:2)
}

// Mount a cache volume for apk cache.
func (r *Apko) WithCache(cache *CacheVolume, opts ...ApkoWithCacheOpts) *Apko { // apko (../../../../../toolchains/release/apko/main.go:61:1)
	assertNotNil("cache", cache)
	q := r.query.Select("withCache")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `sharing` optional argument
		if !querybuilder.IsZeroValue(opts[i].Sharing) {
			q = q.Arg("sharing", opts[i].Sharing)
		}
	}
	q = q.Arg("cache", cache)

	return &Apko{
		query: q,
	}
}

// Add credentials for a registry.
func (r *Apko) WithRegistryAuth(address string, username string, secret *Secret) *Apko { // apko (../../../../../toolchains/release/apko/main.go:87:1)
	assertNotNil("secret", secret)
	q := r.query.Select("withRegistryAuth")
	q = q.Arg("address", address)
	q = q.Arg("username", username)
	q = q.Arg("secret", secret)

	return &Apko{
		query: q,
	}
}

// Removes credentials for a registry.
func (r *Apko) WithoutRegistryAuth(address string) *Apko { // apko (../../../../../toolchains/release/apko/main.go:94:1)
	q := r.query.Select("withoutRegistryAuth")
	q = q.Arg("address", address)

	return &Apko{
		query: q,
	}
}

// Load the Wolfi base configuration.
func (r *Apko) Wolfi() *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:6:1)
	q := r.query.Select("wolfi")

	return &ApkoConfig{
		query: q,
	}
}

type ApkoBuildResult struct { // apko (../../../../../toolchains/release/apko/main.go:251:6)
	query *querybuilder.Selection

	id  *ApkoBuildResultID
	tag *string
}

func (r *ApkoBuildResult) WithGraphQLQuery(q *querybuilder.Selection) *ApkoBuildResult {
	return &ApkoBuildResult{
		query: q,
	}
}

// Import the image into a container.
func (r *ApkoBuildResult) AsContainer() *Container { // apko (../../../../../toolchains/release/apko/main.go:257:1)
	q := r.query.Select("asContainer")

	return &Container{
		query: q,
	}
}

func (r *ApkoBuildResult) File() *File { // apko (../../../../../toolchains/release/apko/main.go:252:2)
	q := r.query.Select("file")

	return &File{
		query: q,
	}
}

// A unique identifier for this ApkoBuildResult.
func (r *ApkoBuildResult) ID(ctx context.Context) (ApkoBuildResultID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ApkoBuildResultID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ApkoBuildResult) XXX_GraphQLType() string {
	return "ApkoBuildResult"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ApkoBuildResult) XXX_GraphQLIDType() string {
	return "ApkoBuildResultID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ApkoBuildResult) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ApkoBuildResult) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ApkoBuildResult) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadApkoBuildResultFromID(ApkoBuildResultID(id))
	return nil
}

func (r *ApkoBuildResult) Tag(ctx context.Context) (string, error) { // apko (../../../../../toolchains/release/apko/main.go:253:2)
	if r.tag != nil {
		return *r.tag, nil
	}
	q := r.query.Select("tag")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type ApkoConfig struct { // apko (../../../../../toolchains/release/apko/config.go:31:6)
	query *querybuilder.Selection

	id *ApkoConfigID
}
type WithApkoConfigFunc func(r *ApkoConfig) *ApkoConfig

// With calls the provided function with current ApkoConfig.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *ApkoConfig) With(f WithApkoConfigFunc) *ApkoConfig {
	return f(r)
}

func (r *ApkoConfig) WithGraphQLQuery(q *querybuilder.Selection) *ApkoConfig {
	return &ApkoConfig{
		query: q,
	}
}

func (r *ApkoConfig) Archs(ctx context.Context) ([]string, error) { // apko (../../../../../toolchains/release/apko/config.go:36:2)
	q := r.query.Select("archs")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Build an image from configuration.
func (r *ApkoConfig) Build(tag string) *ApkoBuildResult { // apko (../../../../../toolchains/release/apko/config.go:79:1)
	q := r.query.Select("build")
	q = q.Arg("tag", tag)

	return &ApkoBuildResult{
		query: q,
	}
}

// Build a container from configuration.
func (r *ApkoConfig) Container() *Container { // apko (../../../../../toolchains/release/apko/config.go:84:1)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

func (r *ApkoConfig) File() *File { // apko (../../../../../toolchains/release/apko/config.go:32:2)
	q := r.query.Select("file")

	return &File{
		query: q,
	}
}

// A unique identifier for this ApkoConfig.
func (r *ApkoConfig) ID(ctx context.Context) (ApkoConfigID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ApkoConfigID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ApkoConfig) XXX_GraphQLType() string {
	return "ApkoConfig"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ApkoConfig) XXX_GraphQLIDType() string {
	return "ApkoConfigID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ApkoConfig) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ApkoConfig) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ApkoConfig) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadApkoConfigFromID(ApkoConfigID(id))
	return nil
}

func (r *ApkoConfig) Keyrings(ctx context.Context) ([]string, error) { // apko (../../../../../toolchains/release/apko/config.go:35:2)
	q := r.query.Select("keyrings")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ApkoConfig) Packages(ctx context.Context) ([]string, error) { // apko (../../../../../toolchains/release/apko/config.go:37:2)
	q := r.query.Select("packages")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ApkoConfig) Repositories(ctx context.Context) ([]string, error) { // apko (../../../../../toolchains/release/apko/config.go:34:2)
	q := r.query.Select("repositories")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Add an arch to the configuration.
func (r *ApkoConfig) WithArch(arch string) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:58:1)
	q := r.query.Select("withArch")
	q = q.Arg("arch", arch)

	return &ApkoConfig{
		query: q,
	}
}

// Add a keyring to the configuration.
func (r *ApkoConfig) WithKeyring(url string) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:51:1)
	q := r.query.Select("withKeyring")
	q = q.Arg("url", url)

	return &ApkoConfig{
		query: q,
	}
}

// Add a package to the configuration.
func (r *ApkoConfig) WithPackage(name string) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:65:1)
	q := r.query.Select("withPackage")
	q = q.Arg("name", name)

	return &ApkoConfig{
		query: q,
	}
}

// Add a list of packages to the configuration.
func (r *ApkoConfig) WithPackages(pkgs []string) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:72:1)
	q := r.query.Select("withPackages")
	q = q.Arg("pkgs", pkgs)

	return &ApkoConfig{
		query: q,
	}
}

// Add a repository to the configuration.
func (r *ApkoConfig) WithRepository(url string) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:44:1)
	q := r.query.Select("withRepository")
	q = q.Arg("url", url)

	return &ApkoConfig{
		query: q,
	}
}

// Retrieve the binding value, as type Apko
func (r *Binding) AsApko() *Apko { // apko (../../../../../toolchains/release/apko/main.go:16:6)
	q := r.query.Select("asApko")

	return &Apko{
		query: q,
	}
}

// Retrieve the binding value, as type ApkoBuildResult
func (r *Binding) AsApkoBuildResult() *ApkoBuildResult { // apko (../../../../../toolchains/release/apko/main.go:251:6)
	q := r.query.Select("asApkoBuildResult")

	return &ApkoBuildResult{
		query: q,
	}
}

// Retrieve the binding value, as type ApkoConfig
func (r *Binding) AsApkoConfig() *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:31:6)
	q := r.query.Select("asApkoConfig")

	return &ApkoConfig{
		query: q,
	}
}

// Create or update a binding of type ApkoBuildResult in the environment
func (r *Env) WithApkoBuildResultInput(name string, value *ApkoBuildResult, description string) *Env { // apko (../../../../../toolchains/release/apko/main.go:251:6)
	assertNotNil("value", value)
	q := r.query.Select("withApkoBuildResultInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ApkoBuildResult output to be assigned in the environment
func (r *Env) WithApkoBuildResultOutput(name string, description string) *Env { // apko (../../../../../toolchains/release/apko/main.go:251:6)
	q := r.query.Select("withApkoBuildResultOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type ApkoConfig in the environment
func (r *Env) WithApkoConfigInput(name string, value *ApkoConfig, description string) *Env { // apko (../../../../../toolchains/release/apko/config.go:31:6)
	assertNotNil("value", value)
	q := r.query.Select("withApkoConfigInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ApkoConfig output to be assigned in the environment
func (r *Env) WithApkoConfigOutput(name string, description string) *Env { // apko (../../../../../toolchains/release/apko/config.go:31:6)
	q := r.query.Select("withApkoConfigOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Apko in the environment
func (r *Env) WithApkoInput(name string, value *Apko, description string) *Env { // apko (../../../../../toolchains/release/apko/main.go:16:6)
	assertNotNil("value", value)
	q := r.query.Select("withApkoInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Apko output to be assigned in the environment
func (r *Env) WithApkoOutput(name string, description string) *Env { // apko (../../../../../toolchains/release/apko/main.go:16:6)
	q := r.query.Select("withApkoOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// ApkoOpts contains options for Query.Apko
type ApkoOpts struct {
	//
	// Custom container to use as a base container.
	//
	Container *Container // apko (../../../../../toolchains/release/apko/main.go:28:2)
	//
	// Disable mounting a default cache volume.
	//
	WithoutCache bool // apko (../../../../../toolchains/release/apko/main.go:33:2)
}

// Build container images from apk packages.
func (r *Query) Apko(opts ...ApkoOpts) *Apko { // apko (../../../../../toolchains/release/apko/main.go:24:1)
	q := r.query.Select("apko")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
		// `withoutCache` optional argument
		if !querybuilder.IsZeroValue(opts[i].WithoutCache) {
			q = q.Arg("withoutCache", opts[i].WithoutCache)
		}
	}

	return &Apko{
		query: q,
	}
}

// Load a ApkoBuildResult from its ID.
func (r *Query) LoadApkoBuildResultFromID(id ApkoBuildResultID) *ApkoBuildResult { // apko (../../../../../toolchains/release/apko/main.go:251:6)
	q := r.query.Select("loadApkoBuildResultFromID")
	q = q.Arg("id", id)

	return &ApkoBuildResult{
		query: q,
	}
}

// Load a ApkoConfig from its ID.
func (r *Query) LoadApkoConfigFromID(id ApkoConfigID) *ApkoConfig { // apko (../../../../../toolchains/release/apko/config.go:31:6)
	q := r.query.Select("loadApkoConfigFromID")
	q = q.Arg("id", id)

	return &ApkoConfig{
		query: q,
	}
}

// Load a Apko from its ID.
func (r *Query) LoadApkoFromID(id ApkoID) *Apko { // apko (../../../../../toolchains/release/apko/main.go:16:6)
	q := r.query.Select("loadApkoFromID")
	q = q.Arg("id", id)

	return &Apko{
		query: q,
	}
}
