// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// A unique identifier for an object.
type NestedDepID = ID // nested-dep (../../../../../../../:0:0)

type NestedDep struct { // nested-dep (../../../../../../../:0:0)
	query *querybuilder.Selection

	failingFunction *Void
	id              *NestedDepID
}

func (r *NestedDep) WithGraphQLQuery(q *querybuilder.Selection) *NestedDep {
	return &NestedDep{
		query: q,
	}
}

func (r *NestedDep) FailingFunction(ctx context.Context) error {
	if r.failingFunction != nil {
		return nil
	}
	q := r.query.Select("failingFunction")

	return q.Execute(ctx)
}

// A unique identifier for this NestedDep.
func (r *NestedDep) ID(ctx context.Context) (NestedDepID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response NestedDepID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *NestedDep) XXX_GraphQLType() string {
	return "NestedDep"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *NestedDep) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *NestedDep) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *NestedDep) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *NestedDep) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = NestedDep{query: selectNode(dag.query, id, "NestedDep")}
	return nil
}

func (r *Query) NestedDep() *NestedDep { // nested-dep (../../../../../../../:0:0)
	q := r.query.Select("nestedDep")

	return &NestedDep{
		query: q,
	}
}
