module github.com/dagger/dagger/sdk/go/e2e

go 1.26.1

// These tests run both with and without a Dagger session already established.
// With: orchestrated from a Dagger module in CI, or under `dagger api exec`.
// Without: `go test ./...` run straight from a shell.
//
// With one, the client attaches to that session and is served whatever API
// schema it already chose; it cannot ask for a different one
// (dagger/dagger#13701). A released dagger.io/dagger pinned here would break
// against this repo's in-development schema, so we build against the client in
// this repo, which matches by construction.
//
// Without one, the client starts its own session, which means downloading the
// CLI version named in sdk/go/engineconn/version.gen.go. That version is
// unpublished between a VERSION bump and its release; export
// _EXPERIMENTAL_DAGGER_CLI_BIN to run in that window.
require dagger.io/dagger v1.0.0-0 // indirect

replace dagger.io/dagger => ..

// Typed client for the engine-dev toolchain module, generated by `dagger api
// client` into internal/dagger/engine-dev from the [[...as-sdk.clients]] entry
// in the workspace dagger.toml.
//
// The generator makes it its own Go module, so it has to be required and
// replaced rather than being a package of this one. It also names it after the
// bound module ("engine-dev"), which is not a path: nothing can resolve it, and
// Go's internal/ rule stops applying. The module line was rewritten by hand to a
// real path, and regeneration keeps it — the generator reads the module name off
// the existing go.mod and generates against it. Tracked as dagger/go-sdk#22, and
// the require/replace pair below as dagger/go-sdk#21.
require github.com/dagger/dagger/sdk/go/e2e/internal/dagger/engine-dev v0.0.0-00010101000000-000000000000

replace github.com/dagger/dagger/sdk/go/e2e/internal/dagger/engine-dev => ./internal/dagger/engine-dev

require (
	github.com/99designs/gqlgen v0.17.89 // indirect
	github.com/Khan/genqlient v0.8.1 // indirect
	github.com/adrg/xdg v0.5.3 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/dagger/querybuilder v0.0.0-20260402040506-574a5e81cb59 // indirect
	github.com/go-logr/logr v1.4.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	github.com/sosodev/duration v1.4.0 // indirect
	github.com/vektah/gqlparser/v2 v2.5.32 // indirect
	go.opentelemetry.io/auto/sdk v1.2.1 // indirect
	go.opentelemetry.io/otel v1.41.0 // indirect
	go.opentelemetry.io/otel/metric v1.41.0 // indirect
	go.opentelemetry.io/otel/trace v1.41.0 // indirect
	golang.org/x/sync v0.20.0 // indirect
	golang.org/x/sys v0.42.0 // indirect
)
