pipeline {
  agent { label 'dagger' }

  stages {
    stage("dagger") {
      steps {
        sh '''
            cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
            dagger run go run main.go
        '''
      }
    }
  }
}
