name = "cli-dev"
engineVersion = "v1.0.0-0"
include = ["../../../go.mod", "../../../go.sum", "../../../util/parallel"]

[runtime]
  source = "go"

[[dependencies]]
  name = "alpine"
  source = "https://github.com/dagger/alpine@main"
  pin = "0cbccf6115c57069e2aa3ef9b07133093f1a3246"

[[dependencies]]
  name = "go"
  source = "../go"

[codegen]
  automaticGitignore = false
