// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"main/internal/dagger/core"
)

// Module for running docker in dagger
type Dockerd = core.Dockerd

// DockerdAttachOpts contains options for Dockerd.Attach
type DockerdAttachOpts = core.DockerdAttachOpts

// DockerdServiceOpts contains options for Dockerd.Service
type DockerdServiceOpts = core.DockerdServiceOpts
