pipeline {
  agent { label 'dagger' }

  stages {
    stage("dagger") {
      steps {
        sh '''
            pip install -r requirements.txt
            python main.py
        '''
      }
    }
  }
}
