version: 2.1
jobs:
  check:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dagger CLI
          command: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - run:
          name: Run Dagger checks
          command: dagger check
workflows:
  dagger:
    jobs:
      - check

# assumes the Dagger Cloud token is
# in a project environment variable named DAGGER_CLOUD_TOKEN
