#!/usr/bin/env bash

set -eu -o pipefail -x

: ${CONTINUOUS_INTEGRATION=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" == "true" ]; then progressFlag="--progress=plain"; fi

export DOCKER_BUILDKIT=1
docker build $progressFlag -f ./hack/dockerfiles/shfmt.Dockerfile --target update -o . .
