{
 "title": "Dagger Engine",
 "description": "https://github.com/dagger/dagger/pull/10652 + https://github.com/dagger/dagger/pull/10555",
 "tags": [ "dagger" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Connected clients",
   "type": "stat",
   "description": "This is typically the `dagger` CLI, but it can be any Dagger API client: https://docs.dagger.io/api",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dagger_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "description": "This is typically the `dagger` CLI, but it can be any Dagger API client: https://docs.dagger.io/api",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "dagger_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached entries",
   "type": "stat",
   "description": "How many entries (layers and volumes) are stored in the local cache: https://docs.dagger.io/configuration/cache/",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dagger_local_cache_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached entries",
   "type": "timeseries",
   "description": "How many entries (layers and volumes) are stored in the local cache: https://docs.dagger.io/configuration/cache/",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "dagger_local_cache_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached data",
   "type": "stat",
   "description": "How much data in bytes (both layers and volumes) is stored in the local cache: https://docs.dagger.io/configuration/cache/",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dagger_local_cache_total_disk_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached data",
   "type": "timeseries",
   "description": "How much data in bytes (both layers and volumes) is stored in the local cache: https://docs.dagger.io/configuration/cache/",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dagger_local_cache_total_disk_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 21 }, "options": { "content": "https://docs.dagger.io" } }
 ]
}