module.exports = {
  current: [
    {
      type: "category",
      label: "Introduction",
      items: ["index", "introduction/use-cases", "introduction/examples"],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "introduction/features/programmability",
        "introduction/features/reusability",
        "introduction/features/caching",
        "introduction/features/observability",
        "introduction/features/sandbox",
        "introduction/features/secrets",
        "introduction/features/llm",
        "introduction/features/shell",
        "introduction/features/toolchains",
      ],
    },
    "introduction/faq",
  ],
  gettingStarted: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/index",
        "getting-started/installation",
        "getting-started/api",
      ],
    },
    {
      type: "category",
      label: "Quickstarts",
      items: [
        "getting-started/quickstarts/basics/index",
        "getting-started/quickstarts/ci/index",
        "getting-started/quickstarts/blueprint/index",
        "getting-started/quickstarts/agent/index",
        "getting-started/quickstarts/agent/inproject",
      ],
    },
    {
      type: "category",
      label: "Calling the Dagger API",
      collapsible: true,
      collapsed: true,
      items: [
        "getting-started/api/clients-cli",
        "getting-started/api/clients-sdk",
        "getting-started/api/clients-http",
      ],
    },
    {
      type: "category",
      label: "Types",
      collapsible: true,
      collapsed: true,
      items: [
        "getting-started/types/index",
        "getting-started/types/container",
        "getting-started/types/directory",
        "getting-started/types/file",
        "getting-started/types/secret",
        "getting-started/types/service",
        "getting-started/types/llm",
        "getting-started/types/env",
        "getting-started/types/cache-volume",
        "getting-started/types/git-repository",
      ],
    },
    {
      type: "category",
      label: "Integrating with CI",
      collapsible: true,
      collapsed: true,
      items: [
        "getting-started/ci-integrations/argo-workflows",
        "getting-started/ci-integrations/aws-codebuild",
        "getting-started/ci-integrations/azure-pipelines",
        "getting-started/ci-integrations/circleci",
        "getting-started/ci-integrations/gitlab",
        "getting-started/ci-integrations/github-actions",
        "getting-started/ci-integrations/github",
        "getting-started/ci-integrations/jenkins",
        "getting-started/ci-integrations/tekton",
      ],
    },
  ],
  extending: [
    {
      type: "category",
      label: "Extending Dagger",
      items: ["extending/index"],
    },
    {
      type: "category",
      label: "Developing Modules",
      items: [
        "extending/modules/modules",
        "extending/modules/functions",
        "extending/modules/arguments",
        "extending/modules/return-types",
        "extending/modules/chaining",
        "extending/modules/secrets",
        "extending/modules/services",
        "extending/modules/cache-volumes",
        "extending/modules/llm",
        "extending/modules/documentation",
        "extending/modules/remote-repositories",
        "extending/modules/module-dependencies",
        "extending/modules/packages",
        "extending/modules/constructors",
        "extending/modules/error-handling",
        "extending/modules/enumerations",
        "extending/modules/custom-types",
        "extending/modules/interfaces",
        "extending/modules/state",
        "extending/modules/function-caching",
        "extending/modules/playground",
        {
          type: "link",
          label: "Module Configuration Schema",
          href: "https://docs.dagger.io/reference/dagger.schema.json",
        },
      ],
    },
    {
      type: "category",
      label: "Custom Applications",
      items: [
        "extending/custom-applications/go",
        "extending/custom-applications/python",
        "extending/custom-applications/typescript",
        "extending/custom-applications/php",
      ],
    },
  ],
  reference: [
    {
      type: "category",
      label: "Reference",
      items: [
        "reference/index",
        "reference/glossary",
        "reference/cli/index",
        "reference/ide-setup",
        "reference/troubleshooting",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      collapsible: true,
      collapsed: true,
      items: [
        "reference/configuration/cloud",
        "reference/configuration/cache",
        "reference/configuration/engine",
        "reference/configuration/llm",
        "reference/configuration/modules",
        "reference/configuration/custom-runner",
        "reference/configuration/custom-ca",
        "reference/configuration/proxy",
        {
          type: "link",
          label: "Engine Configuration Schema",
          href: "https://docs.dagger.io/reference/engine.schema.json",
        },
      ],
    },
    {
      type: "category",
      label: "API and SDKs",
      collapsible: true,
      collapsed: true,
      items: [
        "reference/api/internals",
        {
          type: "link",
          label: "GraphQL API Reference",
          href: "https://docs.dagger.io/api/reference",
        },
        {
          type: "link",
          label: "Go SDK Reference",
          href: "https://pkg.go.dev/dagger.io/dagger",
        },
        {
          type: "link",
          label: "PHP SDK Reference",
          href: "https://docs.dagger.io/reference/php",
        },
        {
          type: "link",
          label: "Python SDK Reference",
          href: "https://dagger-io.readthedocs.org/",
        },
        {
          type: "doc",
          label: "TypeScript SDK Reference",
          id: "reference/typescript/modules",
        },
      ],
    },
    {
      type: "category",
      label: "Container Runtimes",
      collapsible: true,
      collapsed: true,
      items: [
        "reference/container-runtimes/index",
        "reference/container-runtimes/docker",
        "reference/container-runtimes/podman",
        "reference/container-runtimes/nerdctl",
        "reference/container-runtimes/apple-container",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsible: true,
      collapsed: true,
      items: [
        "reference/deployment/kubernetes",
        "reference/deployment/openshift",
      ],
    },
    {
      type: "category",
      label: "Best Practices",
      items: [
        "reference/best-practices/monorepos",
        "reference/best-practices/modules",
        "reference/best-practices/adopting",
        "reference/best-practices/contributing",
      ],
    },
  ],
  cookbook: [
    {
      type: "category",
      label: "Cookbook",
      items: [
        "cookbook/index",
        "cookbook/filesystems",
        "cookbook/containers",
        "cookbook/agents",
        "cookbook/secrets",
        "cookbook/services",
        "cookbook/builds",
        "cookbook/errors",
      ],
    },
  ],
};
