module.exports = {
  current: [
    {
      type: "category",
      label: "Introduction",
      items: ["index", "use-cases", "examples"],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "features/programmability",
        "features/reusability",
        "features/caching",
        "features/observability",
        "features/security",
        "features/secrets",
        "features/llm",
        "features/shell",
      ],
    },
    "faq",
  ],
  gettingStarted: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/index",
        "getting-started/installation",
        "getting-started/api",
      ],
    },
    {
      type: "category",
      label: "Quickstarts",
      items: [
        "getting-started/basics",
        "getting-started/ci",
        "getting-started/agent/index",
        "getting-started/agent/inproject",
      ],
    },
    {
      type: "category",
      label: "Calling the Dagger API",
      items: [
        "extending/clients-cli",
        "extending/clients-sdk",
        "extending/clients-http",
      ],
    },
    {
      type: "category",
      label: "Types",
      items: [
        "types/index",
        "types/container",
        "types/directory",
        "types/file",
        "types/secret",
        "types/service",
        "types/cache-volume",
        "types/llm",
        "types/env",
      ],
    },
    {
      type: "category",
      label: "Integrating with CI",
      items: [
        "integrations/argo-workflows",
        "integrations/aws-codebuild",
        "integrations/azure-pipelines",
        "integrations/circleci",
        "integrations/gitlab",
        "integrations/github-actions",
        "integrations/github",
        "integrations/jenkins",
        "integrations/tekton",
      ],
    },
  ],
  extending: [
    {
      type: "category",
      label: "Extending Dagger",
      items: ["extending/index"],
    },
    {
      type: "category",
      label: "Modules",
      items: [
        "extending/modules",
        "extending/functions",
        "extending/arguments",
        "extending/return-types",
        "extending/chaining",
        "extending/secrets",
        "extending/services",
        "extending/cache-volumes",
        "extending/llm",
        "extending/documentation",
        "extending/remote-repositories",
        "extending/module-dependencies",
        "extending/packages",
        "extending/constructors",
        "extending/error-handling",
        "extending/enumerations",
        "extending/custom-types",
        "extending/interfaces",
        "extending/state",
        "extending/playground",
        {
          type: "link",
          label: "Module Configuration Schema",
          href: "https://docs.dagger.io/reference/dagger.schema.json",
        },
      ],
    },
    {
      type: "category",
      label: "Custom Applications",
      items: [
        "extending/custom-applications/go",
        "extending/custom-applications/python",
        "extending/custom-applications/typescript",
        "extending/custom-applications/php",
      ],
    },
  ],
  reference: [
    {
      type: "category",
      label: "Reference",
      items: [
        "reference/index",
        "reference/glossary",
        "reference/cli/index",
        "reference/ide-setup",
        "reference/troubleshooting",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        "reference/configuration/cloud",
        "reference/configuration/cache",
        "reference/configuration/engine",
        "reference/configuration/llm",
        "reference/configuration/modules",
        "reference/configuration/custom-runner",
        "reference/configuration/custom-ca",
        "reference/configuration/proxy",
        {
          type: "link",
          label: "Engine Configuration Schema",
          href: "https://docs.dagger.io/engine.schema.json",
        },
      ],
    },
    {
      type: "category",
      label: "API and SDKs",
      items: [
        "reference/api/internals",
        {
          type: "link",
          label: "GraphQL API Reference",
          href: "https://docs.dagger.io/api/reference",
        },
        {
          type: "link",
          label: "Go SDK Reference",
          href: "https://pkg.go.dev/dagger.io/dagger",
        },
        {
          type: "link",
          label: "PHP SDK Reference",
          href: "https://docs.dagger.io/reference/php",
        },
        {
          type: "link",
          label: "Python SDK Reference",
          href: "https://dagger-io.readthedocs.org/",
        },
        {
          type: "doc",
          label: "TypeScript SDK Reference",
          id: "reference/typescript/modules",
        },
      ],
    },
    {
      type: "category",
      label: "Container Runtimes",
      items: [
        "reference/container-runtimes/kubernetes",
        "reference/container-runtimes/podman",
        "reference/container-runtimes/nerdctl",
        "reference/container-runtimes/apple-container",
      ],
    },
    {
      type: "category",
      label: "Best Practices",
      items: [
        "reference/best-practices/monorepos",
        "reference/best-practices/modules",
        "reference/best-practices/adopting",
        "reference/best-practices/contributing",
      ],
    },
  ],
  cookbook: [
    {
      type: "category",
      label: "Cookbook",
      items: [
        "cookbook/index",
        "cookbook/filesystems",
        "cookbook/containers",
        "cookbook/agents",
        "cookbook/secrets",
        "cookbook/services",
        "cookbook/builds",
        "cookbook/errors",
      ],
    },
  ],
};
