// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// A unique identifier for an object.
type Sub1ID = ID // sub1 (../../../../../../../../../:0:0)

// A unique identifier for an object.
type Sub1ObjID = ID // sub1 (../../../../../../../../../:0:0)

func (r *Query) Sub1() *Sub1 { // sub1 (../../../../../../../../../:0:0)
	q := r.query.Select("sub1")

	return &Sub1{
		query: q,
	}
}

type Sub1 struct { // sub1 (../../../../../../../../../:0:0)
	query *querybuilder.Selection

	id *Sub1ID
}

func (r *Sub1) WithGraphQLQuery(q *querybuilder.Selection) *Sub1 {
	return &Sub1{
		query: q,
	}
}

func (r *Sub1) Fn(s string) *Sub1Obj {
	q := r.query.Select("fn")
	q = q.Arg("s", s)

	return &Sub1Obj{
		query: q,
	}
}

// A unique identifier for this Sub1.
func (r *Sub1) ID(ctx context.Context) (Sub1ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response Sub1ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Sub1) XXX_GraphQLType() string {
	return "Sub1"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Sub1) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Sub1) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Sub1) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Sub1) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Sub1{query: selectNode(dag.query, id, "Sub1")}
	return nil
}

type Sub1Obj struct { // sub1 (../../../../../../../../../:0:0)
	query *querybuilder.Selection

	foo    *string
	getFoo *string
	id     *Sub1ObjID
}

func (r *Sub1Obj) WithGraphQLQuery(q *querybuilder.Selection) *Sub1Obj {
	return &Sub1Obj{
		query: q,
	}
}

func (r *Sub1Obj) Foo(ctx context.Context) (string, error) {
	if r.foo != nil {
		return *r.foo, nil
	}
	q := r.query.Select("foo")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *Sub1Obj) GetFoo(ctx context.Context) (string, error) {
	if r.getFoo != nil {
		return *r.getFoo, nil
	}
	q := r.query.Select("getFoo")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Sub1Obj.
func (r *Sub1Obj) ID(ctx context.Context) (Sub1ObjID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response Sub1ObjID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Sub1Obj) XXX_GraphQLType() string {
	return "Sub1Obj"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Sub1Obj) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Sub1Obj) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Sub1Obj) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Sub1Obj) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Sub1Obj{query: selectNode(dag.query, id, "Sub1Obj")}
	return nil
}
