// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `CliDevID` scalar type represents an identifier for an object of type CliDev.
type CliDevID string // cli-dev (../../../../toolchains/cli-dev/main.go:83:6)

// Retrieve the binding value, as type CliDev
func (r *Binding) AsCliDev() *CliDev { // cli-dev (../../../../toolchains/cli-dev/main.go:83:6)
	q := r.query.Select("asCliDev")

	return &CliDev{
		query: q,
	}
}

type CliDev struct { // cli-dev (../../../../toolchains/cli-dev/main.go:83:6)
	query *querybuilder.Selection

	id              *CliDevID
	publishMetadata *Void
	releaseDryRun   *Void
	tag             *string
	version         *string
}

func (r *CliDev) WithGraphQLQuery(q *querybuilder.Selection) *CliDev {
	return &CliDev{
		query: q,
	}
}

// CliDevBinaryOpts contains options for CliDev.Binary
type CliDevBinaryOpts struct {
	Platform Platform // cli-dev (../../../../toolchains/cli-dev/main.go:93:2)
}

// Build the dagger CLI binary for a single platform
func (r *CliDev) Binary(opts ...CliDevBinaryOpts) *File { // cli-dev (../../../../toolchains/cli-dev/main.go:91:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `platform` optional argument
		if !querybuilder.IsZeroValue(opts[i].Platform) {
			q = q.Arg("platform", opts[i].Platform)
		}
	}

	return &File{
		query: q,
	}
}

// CliDevDevBinariesOpts contains options for CliDev.DevBinaries
type CliDevDevBinariesOpts struct {
	Platform Platform // cli-dev (../../../../toolchains/cli-dev/main.go:127:2)
}

// Build dev CLI binaries
// TODO: remove this
func (r *CliDev) DevBinaries(opts ...CliDevDevBinariesOpts) *Directory { // cli-dev (../../../../toolchains/cli-dev/main.go:125:1)
	q := r.query.Select("devBinaries")
	for i := len(opts) - 1; i >= 0; i-- {
		// `platform` optional argument
		if !querybuilder.IsZeroValue(opts[i].Platform) {
			q = q.Arg("platform", opts[i].Platform)
		}
	}

	return &Directory{
		query: q,
	}
}

// A unique identifier for this CliDev.
func (r *CliDev) ID(ctx context.Context) (CliDevID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response CliDevID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *CliDev) XXX_GraphQLType() string {
	return "CliDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *CliDev) XXX_GraphQLIDType() string {
	return "CliDevID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *CliDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *CliDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *CliDev) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadCliDevFromID(CliDevID(id))
	return nil
}

// CliDevPublishOpts contains options for CliDev.Publish
type CliDevPublishOpts struct {
	GithubToken *Secret // cli-dev (../../../../toolchains/cli-dev/publish.go:31:2)

	Git *GitRepository // cli-dev (../../../../toolchains/cli-dev/publish.go:33:2)

	AwsAccessKeyID *Secret // cli-dev (../../../../toolchains/cli-dev/publish.go:35:2)

	AwsSecretAccessKey *Secret // cli-dev (../../../../toolchains/cli-dev/publish.go:36:2)

	AwsRegion string // cli-dev (../../../../toolchains/cli-dev/publish.go:37:2)

	AwsBucket string // cli-dev (../../../../toolchains/cli-dev/publish.go:38:2)

	ArtefactsFqdn string // cli-dev (../../../../toolchains/cli-dev/publish.go:39:2)

	DryRun bool // cli-dev (../../../../toolchains/cli-dev/publish.go:41:2)
}

// Publish the CLI using GoReleaser
func (r *CliDev) Publish(tag string, goreleaserKey *Secret, githubOrgName string, opts ...CliDevPublishOpts) *Directory { // cli-dev (../../../../toolchains/cli-dev/publish.go:24:1)
	assertNotNil("goreleaserKey", goreleaserKey)
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `git` optional argument
		if !querybuilder.IsZeroValue(opts[i].Git) {
			q = q.Arg("git", opts[i].Git)
		}
		// `awsAccessKeyId` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsAccessKeyID) {
			q = q.Arg("awsAccessKeyId", opts[i].AwsAccessKeyID)
		}
		// `awsSecretAccessKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsSecretAccessKey) {
			q = q.Arg("awsSecretAccessKey", opts[i].AwsSecretAccessKey)
		}
		// `awsRegion` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsRegion) {
			q = q.Arg("awsRegion", opts[i].AwsRegion)
		}
		// `awsBucket` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsBucket) {
			q = q.Arg("awsBucket", opts[i].AwsBucket)
		}
		// `artefactsFqdn` optional argument
		if !querybuilder.IsZeroValue(opts[i].ArtefactsFqdn) {
			q = q.Arg("artefactsFqdn", opts[i].ArtefactsFqdn)
		}
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
	}
	q = q.Arg("tag", tag)
	q = q.Arg("goreleaserKey", goreleaserKey)
	q = q.Arg("githubOrgName", githubOrgName)

	return &Directory{
		query: q,
	}
}

func (r *CliDev) PublishMetadata(ctx context.Context, awsAccessKeyId *Secret, awsSecretAccessKey *Secret, awsRegion string, awsBucket string, awsCloudfrontDistribution string) error { // cli-dev (../../../../toolchains/cli-dev/publish.go:139:1)
	assertNotNil("awsAccessKeyId", awsAccessKeyId)
	assertNotNil("awsSecretAccessKey", awsSecretAccessKey)
	if r.publishMetadata != nil {
		return nil
	}
	q := r.query.Select("publishMetadata")
	q = q.Arg("awsAccessKeyId", awsAccessKeyId)
	q = q.Arg("awsSecretAccessKey", awsSecretAccessKey)
	q = q.Arg("awsRegion", awsRegion)
	q = q.Arg("awsBucket", awsBucket)
	q = q.Arg("awsCloudfrontDistribution", awsCloudfrontDistribution)

	return q.Execute(ctx)
}

// CliDevReferenceOpts contains options for CliDev.Reference
type CliDevReferenceOpts struct {
	Frontmatter string // cli-dev (../../../../toolchains/cli-dev/main.go:105:2)
	//
	// Include experimental commands
	//
	IncludeExperimental bool // cli-dev (../../../../toolchains/cli-dev/main.go:108:2)
}

// Generate a markdown CLI reference doc
func (r *CliDev) Reference(opts ...CliDevReferenceOpts) *File { // cli-dev (../../../../toolchains/cli-dev/main.go:103:1)
	q := r.query.Select("reference")
	for i := len(opts) - 1; i >= 0; i-- {
		// `frontmatter` optional argument
		if !querybuilder.IsZeroValue(opts[i].Frontmatter) {
			q = q.Arg("frontmatter", opts[i].Frontmatter)
		}
		// `includeExperimental` optional argument
		if !querybuilder.IsZeroValue(opts[i].IncludeExperimental) {
			q = q.Arg("includeExperimental", opts[i].IncludeExperimental)
		}
	}

	return &File{
		query: q,
	}
}

// Verify that the CLI builds without actually publishing anything
func (r *CliDev) ReleaseDryRun(ctx context.Context) error { // cli-dev (../../../../toolchains/cli-dev/publish.go:200:1)
	if r.releaseDryRun != nil {
		return nil
	}
	q := r.query.Select("releaseDryRun")

	return q.Execute(ctx)
}

func (r *CliDev) Tag(ctx context.Context) (string, error) { // cli-dev (../../../../toolchains/cli-dev/main.go:85:2)
	if r.tag != nil {
		return *r.tag, nil
	}
	q := r.query.Select("tag")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *CliDev) Version(ctx context.Context) (string, error) { // cli-dev (../../../../toolchains/cli-dev/main.go:84:2)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Create or update a binding of type CliDev in the environment
func (r *Env) WithCliDevInput(name string, value *CliDev, description string) *Env { // cli-dev (../../../../toolchains/cli-dev/main.go:83:6)
	assertNotNil("value", value)
	q := r.query.Select("withCliDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired CliDev output to be assigned in the environment
func (r *Env) WithCliDevOutput(name string, description string) *Env { // cli-dev (../../../../toolchains/cli-dev/main.go:83:6)
	q := r.query.Select("withCliDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// CliDevOpts contains options for Query.CliDev
type CliDevOpts struct {
	RunnerHost string // cli-dev (../../../../toolchains/cli-dev/main.go:16:2)

	Source *Directory // cli-dev (../../../../toolchains/cli-dev/main.go:37:2)
	//
	// Base image for go build environment
	//
	Base *Container // cli-dev (../../../../toolchains/cli-dev/main.go:41:2)
	//
	// Explicit version to set on the Dagger CLI.
	//
	Version string // cli-dev (../../../../toolchains/cli-dev/main.go:45:2)
}

// Develop the Dagger CLI
func (r *Query) CliDev(opts ...CliDevOpts) *CliDev { // cli-dev (../../../../toolchains/cli-dev/main.go:12:1)
	q := r.query.Select("cliDev")
	for i := len(opts) - 1; i >= 0; i-- {
		// `runnerHost` optional argument
		if !querybuilder.IsZeroValue(opts[i].RunnerHost) {
			q = q.Arg("runnerHost", opts[i].RunnerHost)
		}
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `base` optional argument
		if !querybuilder.IsZeroValue(opts[i].Base) {
			q = q.Arg("base", opts[i].Base)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &CliDev{
		query: q,
	}
}

// Load a CliDev from its ID.
func (r *Query) LoadCliDevFromID(id CliDevID) *CliDev { // cli-dev (../../../../toolchains/cli-dev/main.go:83:6)
	q := r.query.Select("loadCliDevFromID")
	q = q.Arg("id", id)

	return &CliDev{
		query: q,
	}
}
