// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `ElixirSdkDevID` scalar type represents an identifier for an object of type ElixirSdkDev.
type ElixirSDKDevID string // elixir-sdk-dev (../../../../:0:0)

// Retrieve the binding value, as type ElixirSdkDev
func (r *Binding) AsElixirSDKDev() *ElixirSDKDev { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("asElixirSdkDev")

	return &ElixirSDKDev{
		query: q,
	}
}

type ElixirSDKDev struct { // elixir-sdk-dev (../../../../:0:0)
	query *querybuilder.Selection

	baseImage     *string
	codegenTest   *Void
	id            *ElixirSDKDevID
	lint          *Void
	publish       *Void
	releaseDryRun *Void
	sdkTest       *Void
	sourcePath    *string
}

func (r *ElixirSDKDev) WithGraphQLQuery(q *querybuilder.Selection) *ElixirSDKDev {
	return &ElixirSDKDev{
		query: q,
	}
}

func (r *ElixirSDKDev) BaseImage(ctx context.Context) (string, error) { // elixir-sdk-dev (../../../../:0:0)
	if r.baseImage != nil {
		return *r.baseImage, nil
	}
	q := r.query.Select("baseImage")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Bump the Elixir SDK's Engine dependency
func (r *ElixirSDKDev) Bump(version string) *Changeset { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("bump")
	q = q.Arg("version", version)

	return &Changeset{
		query: q,
	}
}

// Regenerate the Elixir SDK API
func (r *ElixirSDKDev) ClientLibrary() *Changeset { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("clientLibrary")

	return &Changeset{
		query: q,
	}
}

// Run dagger_codegen tests
func (r *ElixirSDKDev) CodegenTest(ctx context.Context) error { // elixir-sdk-dev (../../../../:0:0)
	if r.codegenTest != nil {
		return nil
	}
	q := r.query.Select("codegenTest")

	return q.Execute(ctx)
}

func (r *ElixirSDKDev) DevContainer() *Container { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("devContainer")

	return &Container{
		query: q,
	}
}

// A unique identifier for this ElixirSdkDev.
func (r *ElixirSDKDev) ID(ctx context.Context) (ElixirSDKDevID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ElixirSDKDevID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ElixirSDKDev) XXX_GraphQLType() string {
	return "ElixirSdkDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ElixirSDKDev) XXX_GraphQLIDType() string {
	return "ElixirSDKDevID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ElixirSDKDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ElixirSDKDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ElixirSDKDev) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadElixirSDKDevFromID(ElixirSDKDevID(id))
	return nil
}

// Lint the SDK
func (r *ElixirSDKDev) Lint(ctx context.Context) error { // elixir-sdk-dev (../../../../:0:0)
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")

	return q.Execute(ctx)
}

// ElixirSDKDevPublishOpts contains options for ElixirSDKDev.Publish
type ElixirSDKDevPublishOpts struct {
	//
	// Execute a dry-run release, with no side effects
	//
	DryRun bool // elixir-sdk-dev (../../../../:0:0)
}

// Publish the Elixir SDK
func (r *ElixirSDKDev) Publish(ctx context.Context, tag string, hexApiKey *Secret, opts ...ElixirSDKDevPublishOpts) error { // elixir-sdk-dev (../../../../:0:0)
	assertNotNil("hexApiKey", hexApiKey)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
	}
	q = q.Arg("tag", tag)
	q = q.Arg("hexApiKey", hexApiKey)

	return q.Execute(ctx)
}

// Test the publishing process
func (r *ElixirSDKDev) ReleaseDryRun(ctx context.Context) error { // elixir-sdk-dev (../../../../:0:0)
	if r.releaseDryRun != nil {
		return nil
	}
	q := r.query.Select("releaseDryRun")

	return q.Execute(ctx)
}

// Run the SDK tests
func (r *ElixirSDKDev) SDKTest(ctx context.Context) error { // elixir-sdk-dev (../../../../:0:0)
	if r.sdkTest != nil {
		return nil
	}
	q := r.query.Select("sdkTest")

	return q.Execute(ctx)
}

func (r *ElixirSDKDev) Source() *Directory { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

func (r *ElixirSDKDev) SourcePath(ctx context.Context) (string, error) { // elixir-sdk-dev (../../../../:0:0)
	if r.sourcePath != nil {
		return *r.sourcePath, nil
	}
	q := r.query.Select("sourcePath")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Sync Elixir image to keep both dev and runtime modules consistent
func (r *ElixirSDKDev) SyncImage() *File { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("syncImage")

	return &File{
		query: q,
	}
}

// Update codegen test snapshots (auto-accept Mneme changes)
func (r *ElixirSDKDev) UpdateCodegenTests() *Changeset { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("updateCodegenTests")

	return &Changeset{
		query: q,
	}
}

func (r *ElixirSDKDev) Workspace() *Directory { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("workspace")

	return &Directory{
		query: q,
	}
}

// Create or update a binding of type ElixirSdkDev in the environment
func (r *Env) WithElixirSDKDevInput(name string, value *ElixirSDKDev, description string) *Env { // elixir-sdk-dev (../../../../:0:0)
	assertNotNil("value", value)
	q := r.query.Select("withElixirSdkDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ElixirSdkDev output to be assigned in the environment
func (r *Env) WithElixirSDKDevOutput(name string, description string) *Env { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("withElixirSdkDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// ElixirSDKDevOpts contains options for Query.ElixirSDKDev
type ElixirSDKDevOpts struct {
	BaseImage string // elixir-sdk-dev (../../../../:0:0)

	Workspace *Directory // elixir-sdk-dev (../../../../:0:0)

	SourcePath string // elixir-sdk-dev (../../../../:0:0)
}

func (r *Query) ElixirSDKDev(opts ...ElixirSDKDevOpts) *ElixirSDKDev { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("elixirSdkDev")
	for i := len(opts) - 1; i >= 0; i-- {
		// `baseImage` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseImage) {
			q = q.Arg("baseImage", opts[i].BaseImage)
		}
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `sourcePath` optional argument
		if !querybuilder.IsZeroValue(opts[i].SourcePath) {
			q = q.Arg("sourcePath", opts[i].SourcePath)
		}
	}

	return &ElixirSDKDev{
		query: q,
	}
}

// Load a ElixirSdkDev from its ID.
func (r *Query) LoadElixirSDKDevFromID(id ElixirSDKDevID) *ElixirSDKDev { // elixir-sdk-dev (../../../../:0:0)
	q := r.query.Select("loadElixirSdkDevFromID")
	q = q.Arg("id", id)

	return &ElixirSDKDev{
		query: q,
	}
}
