// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"dagger/release/internal/dagger/core"
)

type ElixirClientDev = core.ElixirClientDev

// ElixirClientDevPublishOpts contains options for ElixirClientDev.Publish
type ElixirClientDevPublishOpts = core.ElixirClientDevPublishOpts

// ElixirClientDevOpts contains options for Query.ElixirClientDev
type ElixirClientDevOpts = core.ElixirClientDevOpts
