// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Release(ws *Workspace) *Release { // release (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("release")
	q = q.Arg("ws", ws)

	return &Release{
		query: q,
	}
}

type Release struct { // release (../../../../:0:0)
	query *querybuilder.Selection

	id                       *ID
	notify                   *Void
	publishWithMockEndpoints *Void
}

func (r *Release) WithGraphQLQuery(q *querybuilder.Selection) *Release {
	return &Release{
		query: q,
	}
}

// Regenerate docs files that reference the target Dagger Engine version.
func (r *Release) DocsTargetVersion() *Changeset {
	q := r.query.Select("docsTargetVersion")

	return &Changeset{
		query: q,
	}
}

// Regenerate Elixir SDK files that reference the target Dagger Engine version.
func (r *Release) ElixirSDKTargetVersion() *Changeset {
	q := r.query.Select("elixirSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

// ReleaseGetMaintainersOpts contains options for Release.GetMaintainers
type ReleaseGetMaintainersOpts struct {
	GithubToken *Secret
}

func (r *Release) GetMaintainers(ctx context.Context, githubOrgName string, opts ...ReleaseGetMaintainersOpts) ([]string, error) {
	q := r.query.Select("getMaintainers")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
	}
	q = q.Arg("githubOrgName", githubOrgName)

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Regenerate Go SDK files that reference the target Dagger Engine version.
func (r *Release) GoSDKTargetVersion() *Changeset {
	q := r.query.Select("goSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

// Regenerate Helm chart files that reference the target Dagger Engine version.
func (r *Release) HelmTargetVersion() *Changeset {
	q := r.query.Select("helmTargetVersion")

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Release.
func (r *Release) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Release) XXX_GraphQLType() string {
	return "Release"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Release) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Release) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Release) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Release) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Release{query: selectNode(dag.query, id, "Release")}
	return nil
}

// Regenerate Java SDK files that reference the target Dagger Engine version.
func (r *Release) JavaSDKTargetVersion() *Changeset {
	q := r.query.Select("javaSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

// ReleaseNotifyOpts contains options for Release.Notify
type ReleaseNotifyOpts struct {
	// Discord webhook
	DiscordWebhook *Secret
	// Whether to perform a dry run without creating the release
	DryRun bool
}

func (r *Release) Notify(ctx context.Context, repository string, target string, name string, opts ...ReleaseNotifyOpts) error {
	if r.notify != nil {
		return nil
	}
	q := r.query.Select("notify")
	for i := len(opts) - 1; i >= 0; i-- {
		// `discordWebhook` optional argument
		if !querybuilder.IsZeroValue(opts[i].DiscordWebhook) {
			q = q.Arg("discordWebhook", opts[i].DiscordWebhook)
		}
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
	}
	q = q.Arg("repository", repository)
	q = q.Arg("target", target)
	q = q.Arg("name", name)

	return q.Execute(ctx)
}

// Regenerate PHP SDK files that reference the target Dagger Engine version.
func (r *Release) PhpSDKTargetVersion() *Changeset {
	q := r.query.Select("phpSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

// ReleasePublishOpts contains options for Release.Publish
type ReleasePublishOpts struct {
	DryRun bool

	RegistryImage string

	RegistryUsername string

	RegistryPassword *Secret

	GithubToken *Secret

	GithubOrgName string

	GithubHost string

	GithubCaCert *File

	NetlifyToken *Secret

	NetlifyApiurl string

	PypiToken *Secret

	PypiRepo string

	PypiURL string

	NpmToken *Secret

	NpmRegistryURL string

	HexApikey *Secret

	HexApiurl string

	CargoRegistryToken *Secret

	CargoRegistryIndex string

	GoSDKDestRemote string

	PhpSDKDestRemote string

	AwsAccessKeyID *Secret

	AwsSecretAccessKey *Secret

	AwsRegion string

	AwsBucket string

	AwsCloudfrontDistribution string

	AwsEndpointURL string

	ArtefactsFqdn string

	HelmRegistry string

	DiscordWebhook *Secret
}

func (r *Release) Publish(tag string, commit string, opts ...ReleasePublishOpts) *ReleaseReport {
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
		// `registryImage` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryImage) {
			q = q.Arg("registryImage", opts[i].RegistryImage)
		}
		// `registryUsername` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsername) {
			q = q.Arg("registryUsername", opts[i].RegistryUsername)
		}
		// `registryPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPassword) {
			q = q.Arg("registryPassword", opts[i].RegistryPassword)
		}
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `githubOrgName` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubOrgName) {
			q = q.Arg("githubOrgName", opts[i].GithubOrgName)
		}
		// `githubHost` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubHost) {
			q = q.Arg("githubHost", opts[i].GithubHost)
		}
		// `githubCaCert` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubCaCert) {
			q = q.Arg("githubCaCert", opts[i].GithubCaCert)
		}
		// `netlifyToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].NetlifyToken) {
			q = q.Arg("netlifyToken", opts[i].NetlifyToken)
		}
		// `netlifyApiurl` optional argument
		if !querybuilder.IsZeroValue(opts[i].NetlifyApiurl) {
			q = q.Arg("netlifyApiurl", opts[i].NetlifyApiurl)
		}
		// `pypiToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiToken) {
			q = q.Arg("pypiToken", opts[i].PypiToken)
		}
		// `pypiRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiRepo) {
			q = q.Arg("pypiRepo", opts[i].PypiRepo)
		}
		// `pypiUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].PypiURL) {
			q = q.Arg("pypiUrl", opts[i].PypiURL)
		}
		// `npmToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].NpmToken) {
			q = q.Arg("npmToken", opts[i].NpmToken)
		}
		// `npmRegistryUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].NpmRegistryURL) {
			q = q.Arg("npmRegistryUrl", opts[i].NpmRegistryURL)
		}
		// `hexApikey` optional argument
		if !querybuilder.IsZeroValue(opts[i].HexApikey) {
			q = q.Arg("hexApikey", opts[i].HexApikey)
		}
		// `hexApiurl` optional argument
		if !querybuilder.IsZeroValue(opts[i].HexApiurl) {
			q = q.Arg("hexApiurl", opts[i].HexApiurl)
		}
		// `cargoRegistryToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].CargoRegistryToken) {
			q = q.Arg("cargoRegistryToken", opts[i].CargoRegistryToken)
		}
		// `cargoRegistryIndex` optional argument
		if !querybuilder.IsZeroValue(opts[i].CargoRegistryIndex) {
			q = q.Arg("cargoRegistryIndex", opts[i].CargoRegistryIndex)
		}
		// `goSdkDestRemote` optional argument
		if !querybuilder.IsZeroValue(opts[i].GoSDKDestRemote) {
			q = q.Arg("goSdkDestRemote", opts[i].GoSDKDestRemote)
		}
		// `phpSdkDestRemote` optional argument
		if !querybuilder.IsZeroValue(opts[i].PhpSDKDestRemote) {
			q = q.Arg("phpSdkDestRemote", opts[i].PhpSDKDestRemote)
		}
		// `awsAccessKeyId` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsAccessKeyID) {
			q = q.Arg("awsAccessKeyId", opts[i].AwsAccessKeyID)
		}
		// `awsSecretAccessKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsSecretAccessKey) {
			q = q.Arg("awsSecretAccessKey", opts[i].AwsSecretAccessKey)
		}
		// `awsRegion` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsRegion) {
			q = q.Arg("awsRegion", opts[i].AwsRegion)
		}
		// `awsBucket` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsBucket) {
			q = q.Arg("awsBucket", opts[i].AwsBucket)
		}
		// `awsCloudfrontDistribution` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsCloudfrontDistribution) {
			q = q.Arg("awsCloudfrontDistribution", opts[i].AwsCloudfrontDistribution)
		}
		// `awsEndpointUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].AwsEndpointURL) {
			q = q.Arg("awsEndpointUrl", opts[i].AwsEndpointURL)
		}
		// `artefactsFqdn` optional argument
		if !querybuilder.IsZeroValue(opts[i].ArtefactsFqdn) {
			q = q.Arg("artefactsFqdn", opts[i].ArtefactsFqdn)
		}
		// `helmRegistry` optional argument
		if !querybuilder.IsZeroValue(opts[i].HelmRegistry) {
			q = q.Arg("helmRegistry", opts[i].HelmRegistry)
		}
		// `discordWebhook` optional argument
		if !querybuilder.IsZeroValue(opts[i].DiscordWebhook) {
			q = q.Arg("discordWebhook", opts[i].DiscordWebhook)
		}
	}
	q = q.Arg("tag", tag)
	q = q.Arg("commit", commit)

	return &ReleaseReport{
		query: q,
	}
}

// ReleasePublishWithMockEndpointsOpts contains options for Release.PublishWithMockEndpoints
type ReleasePublishWithMockEndpointsOpts struct {
	// Source tree to publish. The check commits this exact tree to a local git
	// service and invokes release through a nested engine using that git ref.
	Source *Directory
}

// Exercise the release publish path against local mock endpoints.
func (r *Release) PublishWithMockEndpoints(ctx context.Context, opts ...ReleasePublishWithMockEndpointsOpts) error {
	if r.publishWithMockEndpoints != nil {
		return nil
	}
	q := r.query.Select("publishWithMockEndpoints")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return q.Execute(ctx)
}

// Regenerate Python SDK files that reference the target Dagger Engine version.
func (r *Release) PythonSDKTargetVersion() *Changeset {
	q := r.query.Select("pythonSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

// Regenerate Rust SDK files that reference the target Dagger Engine version.
func (r *Release) RustSDKTargetVersion() *Changeset {
	q := r.query.Select("rustSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

// Create a fake release a run checks to catch potential breaking changes.
func (r *Release) TestLocalRelease(version string) *ReleaseTest {
	q := r.query.Select("testLocalRelease")
	q = q.Arg("version", version)

	return &ReleaseTest{
		query: q,
	}
}

// Regenerate TypeScript SDK files that reference the target Dagger Engine version.
func (r *Release) TypescriptSDKTargetVersion() *Changeset {
	q := r.query.Select("typescriptSdkTargetVersion")

	return &Changeset{
		query: q,
	}
}

type ReleaseReport struct { // release (../../../../:0:0)
	query *querybuilder.Selection

	commit   *string
	date     *string
	id       *ID
	markdown *string
	ref      *string
	version  *string
}

func (r *ReleaseReport) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseReport {
	return &ReleaseReport{
		query: q,
	}
}

func (r *ReleaseReport) Artifacts(ctx context.Context) ([]ReleaseReportArtifact, error) {
	q := r.query.Select("artifacts")

	q = q.Select("id")

	type artifacts struct {
		Id ID
	}

	convert := func(fields []artifacts) []ReleaseReportArtifact {
		out := []ReleaseReportArtifact{}

		for i := range fields {
			val := ReleaseReportArtifact{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "ReleaseReportArtifact")
			out = append(out, val)
		}

		return out
	}
	var response []artifacts

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

func (r *ReleaseReport) Commit(ctx context.Context) (string, error) {
	if r.commit != nil {
		return *r.commit, nil
	}
	q := r.query.Select("commit")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Date(ctx context.Context) (string, error) {
	if r.date != nil {
		return *r.date, nil
	}
	q := r.query.Select("date")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Errors(ctx context.Context) ([]Error, error) {
	q := r.query.Select("errors")

	q = q.Select("id")

	type errors struct {
		Id ID
	}

	convert := func(fields []errors) []Error {
		out := []Error{}

		for i := range fields {
			val := Error{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "Error")
			out = append(out, val)
		}

		return out
	}
	var response []errors

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

func (r *ReleaseReport) FollowUps(ctx context.Context) ([]ReleaseReportFollowUp, error) {
	q := r.query.Select("followUps")

	q = q.Select("id")

	type followUps struct {
		Id ID
	}

	convert := func(fields []followUps) []ReleaseReportFollowUp {
		out := []ReleaseReportFollowUp{}

		for i := range fields {
			val := ReleaseReportFollowUp{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "ReleaseReportFollowUp")
			out = append(out, val)
		}

		return out
	}
	var response []followUps

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// A unique identifier for this ReleaseReport.
func (r *ReleaseReport) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseReport) XXX_GraphQLType() string {
	return "ReleaseReport"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseReport) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseReport) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseReport) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseReport) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseReport{query: selectNode(dag.query, id, "ReleaseReport")}
	return nil
}

func (r *ReleaseReport) Markdown(ctx context.Context) (string, error) {
	if r.markdown != nil {
		return *r.markdown, nil
	}
	q := r.query.Select("markdown")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Ref(ctx context.Context) (string, error) {
	if r.ref != nil {
		return *r.ref, nil
	}
	q := r.query.Select("ref")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReport) Version(ctx context.Context) (string, error) {
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type ReleaseReportArtifact struct { // release (../../../../:0:0)
	query *querybuilder.Selection

	id   *ID
	link *string
	name *string
	tag  *string
}

func (r *ReleaseReportArtifact) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseReportArtifact {
	return &ReleaseReportArtifact{
		query: q,
	}
}

func (r *ReleaseReportArtifact) Errors(ctx context.Context) ([]Error, error) {
	q := r.query.Select("errors")

	q = q.Select("id")

	type errors struct {
		Id ID
	}

	convert := func(fields []errors) []Error {
		out := []Error{}

		for i := range fields {
			val := Error{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "Error")
			out = append(out, val)
		}

		return out
	}
	var response []errors

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// A unique identifier for this ReleaseReportArtifact.
func (r *ReleaseReportArtifact) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseReportArtifact) XXX_GraphQLType() string {
	return "ReleaseReportArtifact"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseReportArtifact) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseReportArtifact) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseReportArtifact) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseReportArtifact) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseReportArtifact{query: selectNode(dag.query, id, "ReleaseReportArtifact")}
	return nil
}

func (r *ReleaseReportArtifact) Link(ctx context.Context) (string, error) {
	if r.link != nil {
		return *r.link, nil
	}
	q := r.query.Select("link")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReportArtifact) Name(ctx context.Context) (string, error) {
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReportArtifact) Tag(ctx context.Context) (string, error) {
	if r.tag != nil {
		return *r.tag, nil
	}
	q := r.query.Select("tag")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type ReleaseReportFollowUp struct { // release (../../../../:0:0)
	query *querybuilder.Selection

	id   *ID
	link *string
	name *string
}

func (r *ReleaseReportFollowUp) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseReportFollowUp {
	return &ReleaseReportFollowUp{
		query: q,
	}
}

// A unique identifier for this ReleaseReportFollowUp.
func (r *ReleaseReportFollowUp) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseReportFollowUp) XXX_GraphQLType() string {
	return "ReleaseReportFollowUp"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseReportFollowUp) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseReportFollowUp) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseReportFollowUp) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseReportFollowUp) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseReportFollowUp{query: selectNode(dag.query, id, "ReleaseReportFollowUp")}
	return nil
}

func (r *ReleaseReportFollowUp) Link(ctx context.Context) (string, error) {
	if r.link != nil {
		return *r.link, nil
	}
	q := r.query.Select("link")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *ReleaseReportFollowUp) Name(ctx context.Context) (string, error) {
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type ReleaseTest struct { // release (../../../../:0:0)
	query *querybuilder.Selection

	existingModule *Void
	id             *ID
	newModule      *Void
}

func (r *ReleaseTest) WithGraphQLQuery(q *querybuilder.Selection) *ReleaseTest {
	return &ReleaseTest{
		query: q,
	}
}

func (r *ReleaseTest) Container() *Container {
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// ReleaseTestExistingModuleOpts contains options for ReleaseTest.ExistingModule
type ReleaseTestExistingModuleOpts struct {
	Testdata *Directory
}

// Test calling an existing module with basic commands.
func (r *ReleaseTest) ExistingModule(ctx context.Context, opts ...ReleaseTestExistingModuleOpts) error {
	if r.existingModule != nil {
		return nil
	}
	q := r.query.Select("existingModule")
	for i := len(opts) - 1; i >= 0; i-- {
		// `testdata` optional argument
		if !querybuilder.IsZeroValue(opts[i].Testdata) {
			q = q.Arg("testdata", opts[i].Testdata)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this ReleaseTest.
func (r *ReleaseTest) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ReleaseTest) XXX_GraphQLType() string {
	return "ReleaseTest"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ReleaseTest) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ReleaseTest) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ReleaseTest) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ReleaseTest) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ReleaseTest{query: selectNode(dag.query, id, "ReleaseTest")}
	return nil
}

// Test scaffolding a new module via the Go SDK and executing basic commands.
//
// This installs the Go SDK, uses `dagger module init` with the legacy template
// (the classic ContainerEcho/GrepDir example) to scaffold a module, then calls
// the generated module. Workspace discovery resolves through a .git boundary,
// so the working directory is initialized as a repo first.
func (r *ReleaseTest) NewModule(ctx context.Context) error {
	if r.newModule != nil {
		return nil
	}
	q := r.query.Select("newModule")

	return q.Execute(ctx)
}
