// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"dagger/release/internal/dagger/core"
)

// TypescriptClientDevOpts contains options for Query.TypescriptClientDev
type TypescriptClientDevOpts = core.TypescriptClientDevOpts

type TypescriptClientDev = core.TypescriptClientDev

// TypescriptClientDevLintDocsSnippetsOpts contains options for TypescriptClientDev.LintDocsSnippets
type TypescriptClientDevLintDocsSnippetsOpts = core.TypescriptClientDevLintDocsSnippetsOpts

// TypescriptClientDevNodejsBaseOpts contains options for TypescriptClientDev.NodejsBase
type TypescriptClientDevNodejsBaseOpts = core.TypescriptClientDevNodejsBaseOpts

// TypescriptClientDevNodejsDevContainerOpts contains options for TypescriptClientDev.NodejsDevContainer
type TypescriptClientDevNodejsDevContainerOpts = core.TypescriptClientDevNodejsDevContainerOpts

// TypescriptClientDevReleaseOpts contains options for TypescriptClientDev.Release
type TypescriptClientDevReleaseOpts = core.TypescriptClientDevReleaseOpts
