
extend type Query {
	"Load a secret from its ID"
	secret(id: SecretID!) Secret
}

"A unique identifier for a secret"
scalar SecretID

"A reference to a secret value, which can be handled more safely than the value itself"
type Secret {
	"The identifier for this secret"
	id: SecretID!
}
