# This file was generated. See https://daggerverse.dev/mod/github.com/dagger/dagger/modules/gha
name: docs
"on":
    push:
        branches:
            - main
            - releases/**
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
    workflow_dispatch: {}
permissions:
    contents: read
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
    docs:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-8x16' || 'ubuntu-24.04' }}
            - ${{ github.repository == 'dagger/dagger' && 'namespace-experiments:dagger.integration=enabled;dagger.version=0.19.2' || 'ubuntu-24.04' }}
        name: docs
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.1
              with:
                ssh-private-key: |
                    -----BEGIN OPENSSH PRIVATE KEY-----
                    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
                    QyNTUxOQAAACCTeKOQJcE2/6y4PxEzj6xCJ87EVZoipn1cBW3oi3nb5AAAAJgxDhr3MQ4a
                    9wAAAAtzc2gtZWQyNTUxOQAAACCTeKOQJcE2/6y4PxEzj6xCJ87EVZoipn1cBW3oi3nb5A
                    AAAEBupld98CTSOjzRBXjRyjwBBwP56bVn24rxOmPpIlQnIpN4o5AlwTb/rLg/ETOPrEIn
                    zsRVmiKmfVwFbeiLedvkAAAADnRlc3RAZGFnZ2VyLmlvAQIDBAUGBw==
                    -----END OPENSSH PRIVATE KEY-----
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: --docker-cfg=file:$HOME/.docker/config.json check --targets=docs
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.2
              env:
                SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        timeout-minutes: 20
